/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { SugerApi } from "@fern-api/suger";
import * as core from "../../../../core";

export const Request: core.serialization.Schema<serializers.offer.create.Request.Raw, SugerApi.CreateOfferParams> =
    core.serialization.lazyObject(async () => (await import("../../..")).CreateOfferParams);

export declare namespace Request {
    type Raw = serializers.CreateOfferParams.Raw;
}

export const Response: core.serialization.Schema<serializers.offer.create.Response.Raw, SugerApi.WorkloadOffer> =
    core.serialization.lazyObject(async () => (await import("../../..")).WorkloadOffer);

export declare namespace Response {
    type Raw = serializers.WorkloadOffer.Raw;
}
