/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { SugerApi } from "@fern-api/suger";
import * as core from "../../../../core";

export const EntitlementUsageRecord: core.serialization.ObjectSchema<
    serializers.EntitlementUsageRecord.Raw,
    SugerApi.EntitlementUsageRecord
> = core.serialization.object({
    amounts: core.serialization.list(core.serialization.number()).optional(),
    date: core.serialization.string().optional(),
    keys: core.serialization.list(core.serialization.string()).optional(),
    quantities: core.serialization.list(core.serialization.number()).optional(),
});

export declare namespace EntitlementUsageRecord {
    interface Raw {
        amounts?: number[] | null;
        date?: string | null;
        keys?: string[] | null;
        quantities?: number[] | null;
    }
}
