/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { SugerApi } from "@fern-api/suger";
import * as core from "../../../../core";

export const UsageReport: core.serialization.ObjectSchema<serializers.UsageReport.Raw, SugerApi.UsageReport> =
    core.serialization.object({
        entitlementId: core.serialization.property("entitlementID", core.serialization.string().optional()),
        organizationId: core.serialization.property("organizationID", core.serialization.string().optional()),
        reportDate: core.serialization.string().optional(),
        usageRecords: core.serialization
            .list(core.serialization.lazyObject(async () => (await import("../../..")).EntitlementUsageRecord))
            .optional(),
    });

export declare namespace UsageReport {
    interface Raw {
        entitlementID?: string | null;
        organizationID?: string | null;
        reportDate?: string | null;
        usageRecords?: serializers.EntitlementUsageRecord.Raw[] | null;
    }
}
