/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { SugerApi } from "@fern-api/suger";
import * as core from "../../../../core";

export const UpdateBuyerNameDescriptionParams: core.serialization.ObjectSchema<
    serializers.UpdateBuyerNameDescriptionParams.Raw,
    SugerApi.UpdateBuyerNameDescriptionParams
> = core.serialization.object({
    description: core.serialization.string().optional(),
    id: core.serialization.string().optional(),
    name: core.serialization.string().optional(),
    organizationId: core.serialization.property("organizationID", core.serialization.string().optional()),
});

export declare namespace UpdateBuyerNameDescriptionParams {
    interface Raw {
        description?: string | null;
        id?: string | null;
        name?: string | null;
        organizationID?: string | null;
    }
}
