/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface UpdateBuyerNameDescriptionParams {
    description?: string;
    id?: string;
    name?: string;
    organizationId?: string;
}
