/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { SugerApi } from "@fern-api/suger";
import * as core from "../../../../core";

export const Response: core.serialization.Schema<
    serializers.metering.getUsageRecordGroupById.Response.Raw,
    SugerApi.MeteringUsageRecordGroup
> = core.serialization.lazyObject(async () => (await import("../../..")).MeteringUsageRecordGroup);

export declare namespace Response {
    type Raw = serializers.MeteringUsageRecordGroup.Raw;
}
