/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { SugerApi } from "@fern-api/suger";
import * as core from "../../../../core";

export const Response: core.serialization.Schema<
    serializers.metering.getUsageRecordGroupsForEntitlement.Response.Raw,
    SugerApi.ListUsageRecordGroupsResponse
> = core.serialization.lazyObject(async () => (await import("../../..")).ListUsageRecordGroupsResponse);

export declare namespace Response {
    type Raw = serializers.ListUsageRecordGroupsResponse.Raw;
}
