/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { SugerApi } from "@fern-api/suger";
import * as core from "../../../../core";

export const Request: core.serialization.Schema<
    serializers.metering.reportUsageRecordGroup.Request.Raw,
    SugerApi.CreateUsageRecordGroupParams
> = core.serialization.lazyObject(async () => (await import("../../..")).CreateUsageRecordGroupParams);

export declare namespace Request {
    type Raw = serializers.CreateUsageRecordGroupParams.Raw;
}

export const Response: core.serialization.Schema<
    serializers.metering.reportUsageRecordGroup.Response.Raw,
    SugerApi.MeteringUsageRecordGroup
> = core.serialization.lazyObject(async () => (await import("../../..")).MeteringUsageRecordGroup);

export declare namespace Response {
    type Raw = serializers.MeteringUsageRecordGroup.Raw;
}
