/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { SugerApi } from "@fern-api/suger";
import * as core from "../../../../core";

export const Response: core.serialization.Schema<
    serializers.entitlementTerm.get.Response.Raw,
    SugerApi.WorkloadEntitlementTerm
> = core.serialization.lazyObject(async () => (await import("../../..")).WorkloadEntitlementTerm);

export declare namespace Response {
    type Raw = serializers.WorkloadEntitlementTerm.Raw;
}
