/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { SugerApi } from "@fern-api/suger";
import * as core from "../../../../core";

export const Operation: core.serialization.ObjectSchema<serializers.Operation.Raw, SugerApi.Operation> =
    core.serialization.object({
        endTime: core.serialization.string().optional(),
        id: core.serialization.string().optional(),
        message: core.serialization.string().optional(),
        name: core.serialization.string().optional(),
        startTime: core.serialization.string().optional(),
        status: core.serialization.string().optional(),
        type: core.serialization.string().optional(),
    });

export declare namespace Operation {
    interface Raw {
        endTime?: string | null;
        id?: string | null;
        message?: string | null;
        name?: string | null;
        startTime?: string | null;
        status?: string | null;
        type?: string | null;
    }
}
