/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { SugerApi } from "@fern-api/suger";
import * as core from "../../../../core";

export const UpdateProductParams: core.serialization.ObjectSchema<
    serializers.UpdateProductParams.Raw,
    SugerApi.UpdateProductParams
> = core.serialization.object({
    fulfillmentUrl: core.serialization.string(),
    id: core.serialization.string(),
    organizationId: core.serialization.property("organizationID", core.serialization.string()),
});

export declare namespace UpdateProductParams {
    interface Raw {
        fulfillmentUrl: string;
        id: string;
        organizationID: string;
    }
}
