/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { SugerApi } from "@fern-api/suger";
import * as core from "../../../../core";

export const AddEntitlementCreditResponse: core.serialization.ObjectSchema<
    serializers.AddEntitlementCreditResponse.Raw,
    SugerApi.AddEntitlementCreditResponse
> = core.serialization.object({
    creditAmountIncrement: core.serialization.number().optional(),
    entitlementId: core.serialization.property("entitlementID", core.serialization.string().optional()),
    entitlementTermId: core.serialization.property("entitlementTermID", core.serialization.string().optional()),
    newCreditAmount: core.serialization.number().optional(),
    organizationId: core.serialization.property("organizationID", core.serialization.string().optional()),
});

export declare namespace AddEntitlementCreditResponse {
    interface Raw {
        creditAmountIncrement?: number | null;
        entitlementID?: string | null;
        entitlementTermID?: string | null;
        newCreditAmount?: number | null;
        organizationID?: string | null;
    }
}
