/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { SugerApi } from "@fern-api/suger";
import * as core from "../../../../core";

export const AddEntitlementCreditParams: core.serialization.ObjectSchema<
    serializers.AddEntitlementCreditParams.Raw,
    SugerApi.AddEntitlementCreditParams
> = core.serialization.object({
    creditAmountIncrement: core.serialization.number(),
    entitlementId: core.serialization.property("entitlementID", core.serialization.string()),
    organizationId: core.serialization.property("organizationID", core.serialization.string()),
});

export declare namespace AddEntitlementCreditParams {
    interface Raw {
        creditAmountIncrement: number;
        entitlementID: string;
        organizationID: string;
    }
}
