/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { SugerApi } from "@fern-api/suger";
import * as core from "../../../../core";

export const UpdateEntitlementNameParams: core.serialization.ObjectSchema<
    serializers.UpdateEntitlementNameParams.Raw,
    SugerApi.UpdateEntitlementNameParams
> = core.serialization.object({
    id: core.serialization.string().optional(),
    name: core.serialization.string().optional(),
    organizationId: core.serialization.property("organizationID", core.serialization.string().optional()),
});

export declare namespace UpdateEntitlementNameParams {
    interface Raw {
        id?: string | null;
        name?: string | null;
        organizationID?: string | null;
    }
}
