/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { SugerApi } from "@fern-api/suger";
import * as core from "../../../../core";

export const Request: core.serialization.Schema<
    serializers.apiAuth.getBearerToken.Request.Raw,
    SugerApi.GetApiClientAccessTokenParams
> = core.serialization.lazyObject(async () => (await import("../../..")).GetApiClientAccessTokenParams);

export declare namespace Request {
    type Raw = serializers.GetApiClientAccessTokenParams.Raw;
}

export const Response: core.serialization.Schema<
    serializers.apiAuth.getBearerToken.Response.Raw,
    SugerApi.ApiClientAccessToken
> = core.serialization.lazyObject(async () => (await import("../../..")).ApiClientAccessToken);

export declare namespace Response {
    type Raw = serializers.ApiClientAccessToken.Raw;
}
