/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface GetUsageRecordReportsForEntitlementRequest {
    /**
     * The Entitlement Term ID, if not given, return the UsageRecordReports of all Entitlement Terms under the Entitlement
     */
    entitlementTermId?: string;
}
