/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface GetUsageRecordGroupsForProductRequest {
    /**
     * List pagination size, default 20
     */
    limit?: number;
    /**
     * List pagination offset, default 0
     */
    offset?: number;
}
