/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface AddEntitlementCreditParams {
    creditAmountIncrement: number;
    entitlementId: string;
    organizationId: string;
}
