/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { SugerApi } from "@fern-api/suger";
import * as core from "../../../../core";

export const GetApiClientAccessTokenParams: core.serialization.ObjectSchema<
    serializers.GetApiClientAccessTokenParams.Raw,
    SugerApi.GetApiClientAccessTokenParams
> = core.serialization.object({
    id: core.serialization.string(),
    organizationId: core.serialization.property("organizationID", core.serialization.string()),
    secret: core.serialization.string(),
});

export declare namespace GetApiClientAccessTokenParams {
    interface Raw {
        id: string;
        organizationID: string;
        secret: string;
    }
}
