/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface SearchOperationRequest {
    /**
     * filter by offerId
     */
    offerId?: string;
    /**
     * filter by entitlementId
     */
    entitlementId?: string;
}
