/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { SugerApi } from "@fern-api/suger";
import * as core from "../../../../core";

export const Request: core.serialization.Schema<
    serializers.report.getRevenueReport.Request.Raw,
    SugerApi.GetRevenueReportParams
> = core.serialization.lazyObject(async () => (await import("../../..")).GetRevenueReportParams);

export declare namespace Request {
    type Raw = serializers.GetRevenueReportParams.Raw;
}

export const Response: core.serialization.Schema<
    serializers.report.getRevenueReport.Response.Raw,
    SugerApi.RevenueReport
> = core.serialization.lazyObject(async () => (await import("../../..")).RevenueReport);

export declare namespace Response {
    type Raw = serializers.RevenueReport.Raw;
}
