/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { SugerApi } from "@fern-api/suger";
import * as core from "../../../../core";

export const Request: core.serialization.Schema<
    serializers.report.getUsageReport.Request.Raw,
    SugerApi.GetUsageReportParams
> = core.serialization.lazyObject(async () => (await import("../../..")).GetUsageReportParams);

export declare namespace Request {
    type Raw = serializers.GetUsageReportParams.Raw;
}

export const Response: core.serialization.Schema<serializers.report.getUsageReport.Response.Raw, SugerApi.UsageReport> =
    core.serialization.lazyObject(async () => (await import("../../..")).UsageReport);

export declare namespace Response {
    type Raw = serializers.UsageReport.Raw;
}
