/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface Operation {
    endTime?: string;
    id?: string;
    message?: string;
    name?: string;
    startTime?: string;
    status?: string;
    type?: string;
}
