/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { SugerApi } from "@fern-api/suger";
import * as core from "../../../../core";

export const Request: core.serialization.Schema<
    serializers.integration.create.Request.Raw,
    SugerApi.CreateIntegrationParams
> = core.serialization.lazyObject(async () => (await import("../../..")).CreateIntegrationParams);

export declare namespace Request {
    type Raw = serializers.CreateIntegrationParams.Raw;
}

export const Response: core.serialization.Schema<
    serializers.integration.create.Response.Raw,
    SugerApi.IdentityIntegration
> = core.serialization.lazyObject(async () => (await import("../../..")).IdentityIntegration);

export declare namespace Response {
    type Raw = serializers.IdentityIntegration.Raw;
}
