/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { SugerApi } from "@fern-api/suger";
import * as core from "../../../../core";

export const Request: core.serialization.Schema<
    serializers.integration.update.Request.Raw,
    SugerApi.UpdateIntegrationParams
> = core.serialization.lazyObject(async () => (await import("../../..")).UpdateIntegrationParams);

export declare namespace Request {
    type Raw = serializers.UpdateIntegrationParams.Raw;
}

export const Response: core.serialization.Schema<
    serializers.integration.update.Response.Raw,
    SugerApi.IdentityIntegration
> = core.serialization.lazyObject(async () => (await import("../../..")).IdentityIntegration);

export declare namespace Response {
    type Raw = serializers.IdentityIntegration.Raw;
}
