/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { SugerApi } from "@fern-api/suger";
import * as core from "../../../../core";

export const Response: core.serialization.Schema<serializers.operation.search.Response.Raw, SugerApi.Operation[]> =
    core.serialization.list(core.serialization.lazyObject(async () => (await import("../../..")).Operation));

export declare namespace Response {
    type Raw = serializers.Operation.Raw[];
}
