/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface EntitlementUsageRecord {
    amounts?: number[];
    date?: string;
    keys?: string[];
    quantities?: number[];
}
