/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface GetRevenueReportParams {
    buyerId?: string;
    entitlementId?: string;
    organizationId: string;
    partner: string;
    productId?: string;
    reportType: string;
    service: string;
}
