/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { SugerApi } from "@fern-api/suger";

export interface RevenueReport {
    buyerId?: string;
    entitlementId?: string;
    organizationId?: string;
    partner?: string;
    productId?: string;
    reportDate?: string;
    reportType?: string;
    revenueRecords?: SugerApi.RevenueRecord[];
    service?: string;
}
