/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { SugerApi } from "@fern-api/suger";

export interface UsageReport {
    entitlementId?: string;
    organizationId?: string;
    reportDate?: string;
    usageRecords?: SugerApi.EntitlementUsageRecord[];
}
