/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { SugerApi } from "@fern-api/suger";

export interface AwsAccountIdentifier {
    awsAccountId?: string;
    awsCustomerId?: string;
    companyInfo?: SugerApi.CompanyInfo;
    dataFeedAccountId?: string;
}
