/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The data struct to store integration info for Suger service to access the client's AWS services.
 */
export interface AwsIntegration {
    externalId?: string;
    iamRoleArn?: string;
    marketplaceStartDate?: string;
    mcasFullSyncDone?: boolean;
    mcasIamRoleArn?: string;
    mcasS3Bucket?: string;
    mcasSnsTopic?: string;
    mdfsFullSyncDone?: boolean;
    mdfsKmsKeyArn?: string;
    mdfsS3BucketArn?: string;
    policyArns?: string[];
}
