/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface AwsSaasProductDimension {
    description?: string;
    key?: string;
    name?: string;
    types?: string[];
    unit?: string;
}
