/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface AwsSnsSubscription {
    endpoint?: string;
    protocol?: string;
    status?: string;
    subscriptionArn?: string;
    topicArn?: string;
}
