/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { SugerApi } from "@fern-api/suger";

export interface AwsSaasProduct {
    description?: SugerApi.AwsSaasProductDescription;
    dimensions?: SugerApi.AwsSaasProductDimension[];
    promotionalResources?: SugerApi.AwsSaasProductPromotionalResources;
    supportInformation?: SugerApi.AwsSaasProductSupportInformation;
    versions?: SugerApi.AwsSaasProductVersion[];
    dataFeedProductId?: string;
    productId?: string;
}
