/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface AwsSaasProductDescription {
    associatedProducts?: string;
    categories?: string[];
    euW8Submitted?: boolean;
    highlights?: string[];
    longDescription?: string;
    manufacturer?: string;
    productCode?: string;
    productTitle?: string;
    registered?: boolean;
    searchKeywords?: string[];
    shortDescription?: string;
    sku?: string;
    usW9Submitted?: boolean;
    visibility?: string;
}
