/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { SugerApi } from "@fern-api/suger";

export interface AwsSaasProductPromotionalResources {
    additionalResources?: SugerApi.AwsSaasProductAdditionalResource[];
    logoUrl?: string;
}
