/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { SugerApi } from "@fern-api/suger";

export interface AzureProductVariantPriceSchedule {
    dateTimeRange?: SugerApi.AzureLocalizedTimeRange;
    friendlyName?: string;
    isBaseSchedule?: boolean;
    marketCodes?: string[];
    schedules?: SugerApi.AzurePriceSchedule[];
}
