/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { SugerApi } from "@fern-api/suger";

export interface AzureProductVariant {
    azureGovernmentCertifications?: SugerApi.AzureGovernmentCertification[];
    cloudAvailabilities?: string[];
    conversionPaths?: string;
    extendedProperties?: SugerApi.TypeValue[];
    externalId?: string;
    featureAvailabilities?: SugerApi.AzureProductFeatureAvailability[];
    friendlyName?: string;
    id?: string;
    leadGenId?: string;
    referenceVariantId?: string;
    resourceType?: string;
    state?: string;
}
