/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface AzurePricingUnit {
    isUnlimitedUnit?: boolean;
    lowerUnit?: number;
    name?: string;
    unitType?: string;
    upperUnit?: number;
}
