/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface AzureListingContact {
    email?: string;
    name?: string;
    phone?: string;
    type?: string;
    uri?: string;
}
