/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface AzureProductProperty {
    additionalCategories?: string[];
    appVersion?: string;
    applicableProducts?: string[];
    categories?: string[];
    customAmendments?: string[];
    extendedProperties?: string[];
    globalAmendmentTerms?: string;
    hideKeys?: string[];
    id?: string;
    industries?: string[];
    marketingOnlyChange?: boolean;
    productTags?: string[];
    resourceType?: string;
    submissionVersion?: string;
    termsOfUse?: string;
    useEnterpriseContract?: boolean;
}
