/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface AzureBuyerInfo {
    billingAccountId?: string;
    customerId?: string;
    firstName?: string;
    lastName?: string;
}
