/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface AzureTerm {
    chargeDuration?: string;
    endDate?: string;
    startDate?: string;
    termUnit?: string;
}
