/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { SugerApi } from "@fern-api/suger";

export interface AzureProductVariantTrial {
    dateTimeRange?: SugerApi.AzureLocalizedTimeRange;
    duration?: number;
    durationType?: string;
    type?: string;
}
