/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface AzureProductListingAsset {
    description?: string;
    fileName?: string;
    fileSasUri?: string;
    friendlyName?: string;
    id?: string;
    order?: number;
    publisherDefinedSasUri?: string;
    resourceType?: string;
    state?: string;
    type?: string;
}
