/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { SugerApi } from "@fern-api/suger";

export interface AzureAdIdentifier {
    buyerInfo?: SugerApi.AzureBuyerInfo;
    companyInfo?: SugerApi.CompanyInfo;
    emailId?: string;
    objectId?: string;
    puid?: string;
    tenantId?: string;
}
