/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { SugerApi } from "@fern-api/suger";

export interface AzureProductSubmission {
    areResourcesReady?: boolean;
    friendlyName?: string;
    id?: string;
    pendingUpdateInfo?: SugerApi.AzurePendingUpdateInfo;
    publishedTimeInUtc?: string;
    releaseNumber?: number;
    resourceType?: string;
    resources?: SugerApi.TypeValue[];
    state?: string;
    subState?: string;
    targets?: SugerApi.TypeValue[];
    variantResources?: SugerApi.AzureVariantResource[];
}
