/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { SugerApi } from "@fern-api/suger";

export interface AzureProductListing {
    accessInformation?: string;
    assets?: SugerApi.AzureProductListingAsset[];
    compatibleProducts?: string[];
    description?: string;
    gettingStartedInstructions?: string;
    id?: string;
    keywords?: string[];
    languageCode?: string;
    listingContacts?: SugerApi.AzureListingContact[];
    listingUris?: SugerApi.AzureListingUri[];
    productDisplayName?: string;
    publisherName?: string;
    resourceType?: string;
    shortDescription?: string;
    summary?: string;
    title?: string;
}
