/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { SugerApi } from "@fern-api/suger";

export interface AzureMarketplaceSubscription {
    allowedCustomerOperations?: string[];
    autoRenew?: boolean;
    beneficiary?: SugerApi.AzureAdIdentifier;
    created?: string;
    fulfillmentId?: string;
    id?: string;
    isFreeTrial?: boolean;
    isTest?: boolean;
    lastModified?: string;
    name?: string;
    offerId?: string;
    planId?: string;
    publisherId?: string;
    purchaser?: SugerApi.AzureAdIdentifier;
    quantity?: number;
    saasSubscriptionStatus?: string;
    sandboxType?: string;
    sessionId?: string;
    sessionMode?: string;
    storeFront?: string;
    term?: SugerApi.AzureTerm;
}
