/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { SugerApi } from "@fern-api/suger";

export interface AzurePriceSchedule {
    priceCadence?: SugerApi.AzurePriceCadence;
    pricingModel?: string;
    pricingUnits?: SugerApi.AzurePricingUnit[];
    retailPrice?: SugerApi.AzurePrice;
}
