/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { SugerApi } from "@fern-api/suger";

export interface AzureProductVariantCustomMeter {
    displayName?: string;
    id?: string;
    includedBaseQuantities?: SugerApi.IncludedBaseQuantity[];
    isEnabled?: boolean;
    priceInUsd?: number;
    uniqueId?: string;
    unitOfMeasure?: string;
}
