/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface AzureCredential {
    clientId?: string;
    clientSecret?: string;
    clientSecretKey?: string;
    resourceId?: string;
    tenantId?: string;
}
