/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { SugerApi } from "@fern-api/suger";

export interface AzureLocalizedTimeRange {
    endAt?: SugerApi.AzureLocalizedDateTime;
    startAt?: SugerApi.AzureLocalizedDateTime;
}
