/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface AzureProductPackageConfiguration {
    azureActiveDirectoryApplicationId?: string;
    azureActiveDirectoryTenantId?: string;
    connectionWebhook?: string;
    id?: string;
    landingPageUri?: string;
    resourceType?: string;
}
