/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface AzureProductBranch {
    currentDraftInstanceId?: string;
    friendlyName?: string;
    id?: string;
    module?: string;
    resourceType?: string;
    type?: string;
    variantId?: string;
}
