/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { SugerApi } from "@fern-api/suger";

export interface AzureProductFeatureAvailability {
    customMeters?: SugerApi.AzureProductVariantCustomMeter[];
    id?: string;
    isHidden?: boolean;
    marketStates?: SugerApi.AzureMarketState[];
    markets?: SugerApi.AzureMarket[];
    priceSchedules?: SugerApi.AzureProductVariantPriceSchedule[];
    properties?: SugerApi.TypeValue[];
    resourceType?: string;
    subscriptionAudiences?: SugerApi.AzureAudience[];
    tenantAudiences?: SugerApi.AzureAudience[];
    trial?: SugerApi.AzureProductVariantTrial;
    visibility?: string;
}
