/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { SugerApi } from "@fern-api/suger";

export interface AzureProductSetup {
    callToAction?: string;
    channelStates?: SugerApi.TypeValue[];
    enableTestDrive?: boolean;
    resourceType?: string;
    sellingOption?: string;
    testDriveType?: string;
    trialUri?: string;
}
