/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { SugerApi } from "@fern-api/suger";

export interface BuyerInfo {
    awsBuyer?: SugerApi.AwsAccountIdentifier;
    azureBuyer?: SugerApi.AzureAdIdentifier;
    collectableAmount?: number;
    disbursedAmount?: number;
    gcpBuyer?: SugerApi.GcpMarketplaceUserAccount;
    invoicedAmount?: number;
}
