/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The commit dimension. There may be one or more commit dimensions defined in single product, offer or entitlement.
 */
export interface CommitDimension {
    category?: string;
    description?: string;
    key?: string;
    length?: number;
    maximumUsers?: number;
    minimumUsers?: number;
    name?: string;
    quantity?: number;
    rate?: number;
    timeUnit?: string;
    type?: string;
    types?: string[];
}
