/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface CompanyInfo {
    addressLine1?: string;
    addressLine2?: string;
    city?: string;
    country?: string;
    emailDomain?: string;
    name?: string;
    postalCode?: string;
    state?: string;
}
