/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { SugerApi } from "@fern-api/suger";

export interface EntitlementInfo {
    autoRenew?: boolean;
    awsEntitlements?: SugerApi.Entitlement[];
    azureSubscriptions?: SugerApi.AzureMarketplaceSubscription[];
    collectableAmount?: number;
    commits?: SugerApi.CommitDimension[];
    currency?: string;
    dimensions?: SugerApi.MeteringDimension[];
    disbursedAmount?: number;
    discount?: number;
    eulaType?: string;
    eulaUrl?: string;
    gcpEntitlements?: SugerApi.GcpMarketplaceEntitlement[];
    gcpPlans?: SugerApi.GcpPurchasePlan[];
    invoicedAmount?: number;
    paymentInstallments?: SugerApi.PaymentInstallment[];
    refundCancelationPolicy?: string;
    sellerNotes?: string;
}
