/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface Entitlement {
    customerIdentifier?: string;
    dimension?: string;
    expirationDate?: string;
    productCode?: string;
}
