/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { SugerApi } from "@fern-api/suger";

export interface GcpCommerceProducerPriceInfo {
    description?: string;
    priceModel?: string;
    subscriptionPlans?: SugerApi.GcpCommerceProducerPriceSubscription[];
    usageFees?: SugerApi.GcpCommerceProducerPriceUsage[];
}
