/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { SugerApi } from "@fern-api/suger";

export interface GcpCommerceProducerListingSpec {
    externalAccountSpec?: SugerApi.GcpCommerceProducerExternalAccountSpec;
    listingType?: string;
    marketingSpec?: SugerApi.GcpCommerceProducerMarketingSpec;
    purchaseSpec?: SugerApi.GcpCommerceProducerPurchaseSpec;
}
