/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { SugerApi } from "@fern-api/suger";

export interface GcpCommerceProducerMarketingSpec {
    description?: string;
    displayNames?: string[];
    eulaUrl?: string;
    externalMarketingUrl?: string;
    icon?: string;
    searchCategories?: string[];
    searchDescription?: string;
    searchKeywords?: string[];
    shortTitle?: string;
    supportSpec?: SugerApi.GcpCommerceProducerSupportSpec;
    title?: string;
}
