/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface GcpCommerceProducerExternalAccountSpec {
    loginUri?: string;
    signupUri?: string;
    singleSignOnUri?: string;
}
