/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { SugerApi } from "@fern-api/suger";

export interface GcpCommerceProducerServiceConfig {
    billing?: SugerApi.GcpCommerceProducerServiceBilling;
    metrics?: SugerApi.GcpCommerceProducerPurchaseMetric[];
    name?: string;
    producerProjectId?: string;
    title?: string;
}
