/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface GcpCommerceProducerPurchaseMetric {
    description?: string;
    displayName?: string;
    displayUnit?: string;
    displayUnitDescription?: string;
    id?: string;
    metricKind?: string;
    name?: string;
    reportingUnit?: string;
    unit?: string;
    valueType?: string;
}
