/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { SugerApi } from "@fern-api/suger";

export interface GcpCommerceProducerPriceTier {
    endUsageAmount?: number;
    price?: SugerApi.GcpCommerceProducerPrice;
    startUsageAmount?: number;
}
