/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface GcpIntegration {
    gcpProjectId?: string;
    gcpProjectNumber?: string;
    identityProviderId?: string;
    partnerId?: string;
    pubsubTopic?: string;
    reportBucket?: string;
    reportFullSyncDone?: boolean;
    reportStartDate?: string;
    serviceAccountEmail?: string;
    serviceNames?: string[];
    workloadIdentityPoolId?: string;
}
