/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { SugerApi } from "@fern-api/suger";

export interface GcpMarketplaceUserAccount {
    approvals?: SugerApi.GcpMarketplaceUserAccountApproval[];
    createTime?: string;
    id?: string;
    inputProperties?: number[];
    name?: string;
    provider?: string;
    state?: string;
    updateTime?: string;
    userInfo?: SugerApi.GcpUserInfo;
}
