/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface GcpMarketplaceUserAccountApproval {
    name?: string;
    reason?: string;
    state?: string;
    updateTime?: string;
}
