/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { SugerApi } from "@fern-api/suger";

export interface GcpProduct {
    createTime?: string;
    id?: string;
    listingSpec?: SugerApi.GcpCommerceProducerListingSpec;
    marketplace?: string;
    name?: string;
    service?: string;
    serviceConfig?: SugerApi.GcpCommerceProducerServiceConfig;
}
