/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { SugerApi } from "@fern-api/suger";

export interface GcpPurchasePlan {
    name?: string;
    priceInfo?: SugerApi.GcpCommerceProducerPriceInfo;
    purchaseMode?: string;
    title?: string;
}
