/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { SugerApi } from "@fern-api/suger";

export interface IdentityIntegration {
    createdBy?: string;
    creationTime?: string;
    info?: SugerApi.IntegrationInfo;
    lastUpdateTime?: string;
    lastUpdatedBy?: string;
    organizationId?: string;
    partner?: string;
    service?: string;
    status?: string;
}
