/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { SugerApi } from "@fern-api/suger";

export interface IdentityBuyer {
    creationTime?: string;
    description?: string;
    externalId?: string;
    id?: string;
    info?: SugerApi.BuyerInfo;
    lastUpdateTime?: string;
    name?: string;
    organizationId?: string;
    partner?: string;
}
