/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface MeteringUsageRecordGroup {
    creationTime?: string;
    entitlementId?: string;
    id?: string;
    lastUpdateTime?: string;
    organizationId?: string;
    serialId?: number;
    status?: string;
    usageRecordReportId?: string;
}
