/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { SugerApi } from "@fern-api/suger";

export interface MeteringUsageRecordReport {
    creationTime?: string;
    entitlementId?: string;
    entitlementTermId?: string;
    id?: string;
    info?: SugerApi.MeteringUsageRecordReportInfo;
    organizationId?: string;
    productId?: string;
}
