/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { SugerApi } from "@fern-api/suger";

/**
 * The dimension to meter usage in entitlement.
 */
export interface MeteringDimension {
    category?: string;
    description?: string;
    includedBaseQuantities?: SugerApi.IncludedBaseQuantity[];
    key?: string;
    name?: string;
    rate?: number;
    types?: string[];
    usageCount?: SugerApi.UsageCount;
    valueType?: string;
}
