/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { SugerApi } from "@fern-api/suger";

export interface ProductInfo {
    awsSaasProduct?: SugerApi.AwsSaasProduct;
    awsSnsSubscriptions?: SugerApi.AwsSnsSubscription[];
    azureProduct?: SugerApi.AzureProduct;
    commits?: SugerApi.CommitDimension[];
    currency?: string;
    dimensions?: SugerApi.MeteringDimension[];
    eulaUrl?: string;
    gcpProduct?: SugerApi.GcpProduct;
    refundCancelationPolicy?: string;
    sellerNotes?: string;
}
