/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { SugerApi } from "@fern-api/suger";

export interface UsageRecord {
    customerIdentifier?: string;
    dimension?: string;
    quantity?: number;
    timestamp?: string;
    usageAllocations?: SugerApi.UsageAllocation[];
}
