/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { SugerApi } from "@fern-api/suger";

export interface UsageEventConflictResponse {
    additionalInfo?: SugerApi.UsageEventConflictResponseAdditionalInfo;
    code?: string;
    message?: string;
}
