/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { SugerApi } from "@fern-api/suger";

export interface UsageBatchEventOkMessage {
    dimension?: string;
    effectiveStartTime?: string;
    error?: SugerApi.UsageEventConflictResponse;
    messageTime?: string;
    planId?: string;
    quantity?: number;
    resourceId?: string;
    resourceUri?: string;
    status?: string;
    usageEventId?: string;
}
