/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { SugerApi } from "@fern-api/suger";

export interface UsageRecordResult {
    meteringRecordId?: string;
    status?: string;
    usageRecord?: SugerApi.UsageRecord;
}
