/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { SugerApi } from "@fern-api/suger";

export interface WorkloadEntitlementTerm {
    buyerId?: string;
    commitAmount?: number;
    creditAmount?: number;
    endTime?: string;
    entitlementId?: string;
    entitlementInfo?: SugerApi.EntitlementInfo;
    externalEntitlementId?: string;
    id?: string;
    info?: SugerApi.EntitlementTermInfo;
    offerId?: string;
    organizationId?: string;
    partner?: string;
    productId?: string;
    service?: string;
    startTime?: string;
    usedCommitAmount?: number;
    usedCreditAmount?: number;
}
