/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { SugerApi } from "@fern-api/suger";

export interface WorkloadProduct {
    createdBy?: string;
    creationTime?: string;
    externalId?: string;
    fulfillmentUrl?: string;
    id?: string;
    info?: SugerApi.ProductInfo;
    lastUpdateTime?: string;
    lastUpdatedBy?: string;
    name?: string;
    organizationId?: string;
    partner?: string;
    productType?: string;
    service?: string;
    status?: string;
}
