/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { SugerApi } from "@fern-api/suger";

export interface WorkloadOffer {
    createdBy?: string;
    creationTime?: string;
    endTime?: string;
    expireTime?: string;
    externalId?: string;
    id?: string;
    info?: SugerApi.OfferInfo;
    lastUpdateTime?: string;
    lastUpdatedBy?: string;
    name?: string;
    offerType?: string;
    organizationId?: string;
    partner?: string;
    productId?: string;
    service?: string;
    status?: string;
}
