/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { SugerApi } from "@fern-api/suger";

export interface WorkloadEntitlement {
    buyerId?: string;
    creationTime?: string;
    endTime?: string;
    entitlementTermId?: string;
    externalBuyerId?: string;
    externalId?: string;
    externalProductId?: string;
    id?: string;
    info?: SugerApi.EntitlementInfo;
    lastUpdateTime?: string;
    name?: string;
    offerId?: string;
    organizationId?: string;
    partner?: string;
    productId?: string;
    service?: string;
    startTime?: string;
    status?: string;
    type?: string;
}
