/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "./environments";
import * as core from "./core";
import { Client as ApiAuthClient } from "./api/resources/apiAuth/client/Client";
import { Client as BuyerClient } from "./api/resources/buyer/client/Client";
import { Client as EntitlementClient } from "./api/resources/entitlement/client/Client";
import { Client as EntitlementTermClient } from "./api/resources/entitlementTerm/client/Client";
import { Client as IntegrationClient } from "./api/resources/integration/client/Client";
import { Client as MeteringClient } from "./api/resources/metering/client/Client";
import { Client as OfferClient } from "./api/resources/offer/client/Client";
import { Client as OperationClient } from "./api/resources/operation/client/Client";
import { Client as ProductClient } from "./api/resources/product/client/Client";
import { Client as ReportClient } from "./api/resources/report/client/Client";

export declare namespace SugerApiClient {
    interface Options {
        environment?: environments.SugerApiEnvironment | string;
        token?: core.Supplier<core.BearerToken>;
    }
}

export class SugerApiClient {
    constructor(private readonly options: SugerApiClient.Options) {}

    #apiAuth: ApiAuthClient | undefined;

    public get apiAuth(): ApiAuthClient {
        return (this.#apiAuth ??= new ApiAuthClient(this.options));
    }

    #buyer: BuyerClient | undefined;

    public get buyer(): BuyerClient {
        return (this.#buyer ??= new BuyerClient(this.options));
    }

    #entitlement: EntitlementClient | undefined;

    public get entitlement(): EntitlementClient {
        return (this.#entitlement ??= new EntitlementClient(this.options));
    }

    #entitlementTerm: EntitlementTermClient | undefined;

    public get entitlementTerm(): EntitlementTermClient {
        return (this.#entitlementTerm ??= new EntitlementTermClient(this.options));
    }

    #integration: IntegrationClient | undefined;

    public get integration(): IntegrationClient {
        return (this.#integration ??= new IntegrationClient(this.options));
    }

    #metering: MeteringClient | undefined;

    public get metering(): MeteringClient {
        return (this.#metering ??= new MeteringClient(this.options));
    }

    #offer: OfferClient | undefined;

    public get offer(): OfferClient {
        return (this.#offer ??= new OfferClient(this.options));
    }

    #operation: OperationClient | undefined;

    public get operation(): OperationClient {
        return (this.#operation ??= new OperationClient(this.options));
    }

    #product: ProductClient | undefined;

    public get product(): ProductClient {
        return (this.#product ??= new ProductClient(this.options));
    }

    #report: ReportClient | undefined;

    public get report(): ReportClient {
        return (this.#report ??= new ReportClient(this.options));
    }
}
