/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const SugerApiEnvironment = {
    Production: "http://www.suger.io",
} as const;

export type SugerApiEnvironment = typeof SugerApiEnvironment.Production;
