/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { SugerApi } from "@fern-api/suger";
import * as core from "../../../../core";

export const CreateUsageRecordGroupParams: core.serialization.ObjectSchema<
    serializers.CreateUsageRecordGroupParams.Raw,
    SugerApi.CreateUsageRecordGroupParams
> = core.serialization.object({
    entitlementId: core.serialization.property("entitlementID", core.serialization.string()),
    id: core.serialization.string().optional(),
    organizationId: core.serialization.property("organizationID", core.serialization.string()),
});

export declare namespace CreateUsageRecordGroupParams {
    interface Raw {
        entitlementID: string;
        id?: string | null;
        organizationID: string;
    }
}
