/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { SugerApi } from "@fern-api/suger";

export interface CreateIntegrationParams {
    info: SugerApi.IntegrationInfo;
    organizationId: string;
    partner: string;
    service: string;
}
