/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { SugerApi } from "@fern-api/suger";
import * as core from "../../../../core";

export const AwsAccountIdentifier: core.serialization.ObjectSchema<
    serializers.AwsAccountIdentifier.Raw,
    SugerApi.AwsAccountIdentifier
> = core.serialization.object({
    awsAccountId: core.serialization.property("awsAccountID", core.serialization.string().optional()),
    awsCustomerId: core.serialization.property("awsCustomerID", core.serialization.string().optional()),
    companyInfo: core.serialization.lazyObject(async () => (await import("../../..")).CompanyInfo).optional(),
    dataFeedAccountId: core.serialization.property("dataFeedAccountID", core.serialization.string().optional()),
});

export declare namespace AwsAccountIdentifier {
    interface Raw {
        awsAccountID?: string | null;
        awsCustomerID?: string | null;
        companyInfo?: serializers.CompanyInfo.Raw | null;
        dataFeedAccountID?: string | null;
    }
}
