/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { SugerApi } from "@fern-api/suger";
import * as core from "../../../../core";

export const AwsIntegration: core.serialization.ObjectSchema<serializers.AwsIntegration.Raw, SugerApi.AwsIntegration> =
    core.serialization.object({
        externalId: core.serialization.property("externalID", core.serialization.string().optional()),
        iamRoleArn: core.serialization.string().optional(),
        marketplaceStartDate: core.serialization.string().optional(),
        mcasFullSyncDone: core.serialization.boolean().optional(),
        mcasIamRoleArn: core.serialization.string().optional(),
        mcasS3Bucket: core.serialization.string().optional(),
        mcasSnsTopic: core.serialization.string().optional(),
        mdfsFullSyncDone: core.serialization.boolean().optional(),
        mdfsKmsKeyArn: core.serialization.string().optional(),
        mdfsS3BucketArn: core.serialization.string().optional(),
        policyArns: core.serialization.list(core.serialization.string()).optional(),
    });

export declare namespace AwsIntegration {
    interface Raw {
        externalID?: string | null;
        iamRoleArn?: string | null;
        marketplaceStartDate?: string | null;
        mcasFullSyncDone?: boolean | null;
        mcasIamRoleArn?: string | null;
        mcasS3Bucket?: string | null;
        mcasSnsTopic?: string | null;
        mdfsFullSyncDone?: boolean | null;
        mdfsKmsKeyArn?: string | null;
        mdfsS3BucketArn?: string | null;
        policyArns?: string[] | null;
    }
}
