/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { SugerApi } from "@fern-api/suger";
import * as core from "../../../../core";

export const AwsSaasProductDescription: core.serialization.ObjectSchema<
    serializers.AwsSaasProductDescription.Raw,
    SugerApi.AwsSaasProductDescription
> = core.serialization.object({
    associatedProducts: core.serialization.property("AssociatedProducts", core.serialization.string().optional()),
    categories: core.serialization.property(
        "Categories",
        core.serialization.list(core.serialization.string()).optional()
    ),
    euW8Submitted: core.serialization.property("EuW8Submitted", core.serialization.boolean().optional()),
    highlights: core.serialization.property(
        "Highlights",
        core.serialization.list(core.serialization.string()).optional()
    ),
    longDescription: core.serialization.property("LongDescription", core.serialization.string().optional()),
    manufacturer: core.serialization.property("Manufacturer", core.serialization.string().optional()),
    productCode: core.serialization.property("ProductCode", core.serialization.string().optional()),
    productTitle: core.serialization.property("ProductTitle", core.serialization.string().optional()),
    registered: core.serialization.property("Registered", core.serialization.boolean().optional()),
    searchKeywords: core.serialization.property(
        "SearchKeywords",
        core.serialization.list(core.serialization.string()).optional()
    ),
    shortDescription: core.serialization.property("ShortDescription", core.serialization.string().optional()),
    sku: core.serialization.property("Sku", core.serialization.string().optional()),
    usW9Submitted: core.serialization.property("UsW9Submitted", core.serialization.boolean().optional()),
    visibility: core.serialization.property("Visibility", core.serialization.string().optional()),
});

export declare namespace AwsSaasProductDescription {
    interface Raw {
        AssociatedProducts?: string | null;
        Categories?: string[] | null;
        EuW8Submitted?: boolean | null;
        Highlights?: string[] | null;
        LongDescription?: string | null;
        Manufacturer?: string | null;
        ProductCode?: string | null;
        ProductTitle?: string | null;
        Registered?: boolean | null;
        SearchKeywords?: string[] | null;
        ShortDescription?: string | null;
        Sku?: string | null;
        UsW9Submitted?: boolean | null;
        Visibility?: string | null;
    }
}
