/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { SugerApi } from "@fern-api/suger";
import * as core from "../../../../core";

export const AwsSaasProductDimension: core.serialization.ObjectSchema<
    serializers.AwsSaasProductDimension.Raw,
    SugerApi.AwsSaasProductDimension
> = core.serialization.object({
    description: core.serialization.property("Description", core.serialization.string().optional()),
    key: core.serialization.property("Key", core.serialization.string().optional()),
    name: core.serialization.property("Name", core.serialization.string().optional()),
    types: core.serialization.property("Types", core.serialization.list(core.serialization.string()).optional()),
    unit: core.serialization.property("Unit", core.serialization.string().optional()),
});

export declare namespace AwsSaasProductDimension {
    interface Raw {
        Description?: string | null;
        Key?: string | null;
        Name?: string | null;
        Types?: string[] | null;
        Unit?: string | null;
    }
}
