/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { SugerApi } from "@fern-api/suger";
import * as core from "../../../../core";

export const AwsSaasProductAdditionalResource: core.serialization.ObjectSchema<
    serializers.AwsSaasProductAdditionalResource.Raw,
    SugerApi.AwsSaasProductAdditionalResource
> = core.serialization.object({
    text: core.serialization.property("Text", core.serialization.string().optional()),
    type: core.serialization.property("Type", core.serialization.string().optional()),
    url: core.serialization.property("Url", core.serialization.string().optional()),
});

export declare namespace AwsSaasProductAdditionalResource {
    interface Raw {
        Text?: string | null;
        Type?: string | null;
        Url?: string | null;
    }
}
