/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { SugerApi } from "@fern-api/suger";
import * as core from "../../../../core";

export const AwsSaasProductPromotionalResources: core.serialization.ObjectSchema<
    serializers.AwsSaasProductPromotionalResources.Raw,
    SugerApi.AwsSaasProductPromotionalResources
> = core.serialization.object({
    additionalResources: core.serialization.property(
        "AdditionalResources",
        core.serialization
            .list(
                core.serialization.lazyObject(async () => (await import("../../..")).AwsSaasProductAdditionalResource)
            )
            .optional()
    ),
    logoUrl: core.serialization.property("LogoUrl", core.serialization.string().optional()),
});

export declare namespace AwsSaasProductPromotionalResources {
    interface Raw {
        AdditionalResources?: serializers.AwsSaasProductAdditionalResource.Raw[] | null;
        LogoUrl?: string | null;
    }
}
