/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { SugerApi } from "@fern-api/suger";
import * as core from "../../../../core";

export const AwsSaasProductSupportInformation: core.serialization.ObjectSchema<
    serializers.AwsSaasProductSupportInformation.Raw,
    SugerApi.AwsSaasProductSupportInformation
> = core.serialization.object({
    description: core.serialization.property("Description", core.serialization.string().optional()),
});

export declare namespace AwsSaasProductSupportInformation {
    interface Raw {
        Description?: string | null;
    }
}
