/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { SugerApi } from "@fern-api/suger";
import * as core from "../../../../core";

export const AwsSaasProductDeliveryOption: core.serialization.ObjectSchema<
    serializers.AwsSaasProductDeliveryOption.Raw,
    SugerApi.AwsSaasProductDeliveryOption
> = core.serialization.object({
    fulfillmentUrl: core.serialization.property("FulfillmentUrl", core.serialization.string().optional()),
    id: core.serialization.property("Id", core.serialization.string().optional()),
    type: core.serialization.property("Type", core.serialization.string().optional()),
});

export declare namespace AwsSaasProductDeliveryOption {
    interface Raw {
        FulfillmentUrl?: string | null;
        Id?: string | null;
        Type?: string | null;
    }
}
