/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { SugerApi } from "@fern-api/suger";
import * as core from "../../../../core";

export const AwsSnsSubscription: core.serialization.ObjectSchema<
    serializers.AwsSnsSubscription.Raw,
    SugerApi.AwsSnsSubscription
> = core.serialization.object({
    endpoint: core.serialization.property("Endpoint", core.serialization.string().optional()),
    protocol: core.serialization.property("Protocol", core.serialization.string().optional()),
    status: core.serialization.property("Status", core.serialization.string().optional()),
    subscriptionArn: core.serialization.property("SubscriptionArn", core.serialization.string().optional()),
    topicArn: core.serialization.property("TopicArn", core.serialization.string().optional()),
});

export declare namespace AwsSnsSubscription {
    interface Raw {
        Endpoint?: string | null;
        Protocol?: string | null;
        Status?: string | null;
        SubscriptionArn?: string | null;
        TopicArn?: string | null;
    }
}
