/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { SugerApi } from "@fern-api/suger";
import * as core from "../../../../core";

export const AwsSaasProductVersion: core.serialization.ObjectSchema<
    serializers.AwsSaasProductVersion.Raw,
    SugerApi.AwsSaasProductVersion
> = core.serialization.object({
    deliveryOptions: core.serialization.property(
        "DeliveryOptions",
        core.serialization
            .list(core.serialization.lazyObject(async () => (await import("../../..")).AwsSaasProductDeliveryOption))
            .optional()
    ),
    id: core.serialization.property("Id", core.serialization.string().optional()),
});

export declare namespace AwsSaasProductVersion {
    interface Raw {
        DeliveryOptions?: serializers.AwsSaasProductDeliveryOption.Raw[] | null;
        Id?: string | null;
    }
}
