/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { SugerApi } from "@fern-api/suger";
import * as core from "../../../../core";

export const AzurePricingUnit: core.serialization.ObjectSchema<
    serializers.AzurePricingUnit.Raw,
    SugerApi.AzurePricingUnit
> = core.serialization.object({
    isUnlimitedUnit: core.serialization.boolean().optional(),
    lowerUnit: core.serialization.number().optional(),
    name: core.serialization.string().optional(),
    unitType: core.serialization.string().optional(),
    upperUnit: core.serialization.number().optional(),
});

export declare namespace AzurePricingUnit {
    interface Raw {
        isUnlimitedUnit?: boolean | null;
        lowerUnit?: number | null;
        name?: string | null;
        unitType?: string | null;
        upperUnit?: number | null;
    }
}
