/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { SugerApi } from "@fern-api/suger";
import * as core from "../../../../core";

export const AzureMarketplaceSubscription: core.serialization.ObjectSchema<
    serializers.AzureMarketplaceSubscription.Raw,
    SugerApi.AzureMarketplaceSubscription
> = core.serialization.object({
    allowedCustomerOperations: core.serialization.list(core.serialization.string()).optional(),
    autoRenew: core.serialization.boolean().optional(),
    beneficiary: core.serialization.lazyObject(async () => (await import("../../..")).AzureAdIdentifier).optional(),
    created: core.serialization.string().optional(),
    fulfillmentId: core.serialization.string().optional(),
    id: core.serialization.string().optional(),
    isFreeTrial: core.serialization.boolean().optional(),
    isTest: core.serialization.boolean().optional(),
    lastModified: core.serialization.string().optional(),
    name: core.serialization.string().optional(),
    offerId: core.serialization.string().optional(),
    planId: core.serialization.string().optional(),
    publisherId: core.serialization.string().optional(),
    purchaser: core.serialization.lazyObject(async () => (await import("../../..")).AzureAdIdentifier).optional(),
    quantity: core.serialization.number().optional(),
    saasSubscriptionStatus: core.serialization.string().optional(),
    sandboxType: core.serialization.string().optional(),
    sessionId: core.serialization.string().optional(),
    sessionMode: core.serialization.string().optional(),
    storeFront: core.serialization.string().optional(),
    term: core.serialization.lazyObject(async () => (await import("../../..")).AzureTerm).optional(),
});

export declare namespace AzureMarketplaceSubscription {
    interface Raw {
        allowedCustomerOperations?: string[] | null;
        autoRenew?: boolean | null;
        beneficiary?: serializers.AzureAdIdentifier.Raw | null;
        created?: string | null;
        fulfillmentId?: string | null;
        id?: string | null;
        isFreeTrial?: boolean | null;
        isTest?: boolean | null;
        lastModified?: string | null;
        name?: string | null;
        offerId?: string | null;
        planId?: string | null;
        publisherId?: string | null;
        purchaser?: serializers.AzureAdIdentifier.Raw | null;
        quantity?: number | null;
        saasSubscriptionStatus?: string | null;
        sandboxType?: string | null;
        sessionId?: string | null;
        sessionMode?: string | null;
        storeFront?: string | null;
        term?: serializers.AzureTerm.Raw | null;
    }
}
