/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { SugerApi } from "@fern-api/suger";
import * as core from "../../../../core";

export const AzureLocalizedDateTime: core.serialization.ObjectSchema<
    serializers.AzureLocalizedDateTime.Raw,
    SugerApi.AzureLocalizedDateTime
> = core.serialization.object({
    dateTimeInUtc: core.serialization.string().optional(),
    localizePerMarket: core.serialization.boolean().optional(),
});

export declare namespace AzureLocalizedDateTime {
    interface Raw {
        dateTimeInUtc?: string | null;
        localizePerMarket?: boolean | null;
    }
}
