/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { SugerApi } from "@fern-api/suger";
import * as core from "../../../../core";

export const AzureGovernmentCertification: core.serialization.ObjectSchema<
    serializers.AzureGovernmentCertification.Raw,
    SugerApi.AzureGovernmentCertification
> = core.serialization.object({
    title: core.serialization.string().optional(),
    uri: core.serialization.string().optional(),
    validationResults: core.serialization
        .list(core.serialization.lazyObject(async () => (await import("../../..")).AzureValidationResult))
        .optional(),
});

export declare namespace AzureGovernmentCertification {
    interface Raw {
        title?: string | null;
        uri?: string | null;
        validationResults?: serializers.AzureValidationResult.Raw[] | null;
    }
}
