/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { SugerApi } from "@fern-api/suger";
import * as core from "../../../../core";

export const AzureLocalizedTimeRange: core.serialization.ObjectSchema<
    serializers.AzureLocalizedTimeRange.Raw,
    SugerApi.AzureLocalizedTimeRange
> = core.serialization.object({
    endAt: core.serialization.lazyObject(async () => (await import("../../..")).AzureLocalizedDateTime).optional(),
    startAt: core.serialization.lazyObject(async () => (await import("../../..")).AzureLocalizedDateTime).optional(),
});

export declare namespace AzureLocalizedTimeRange {
    interface Raw {
        endAt?: serializers.AzureLocalizedDateTime.Raw | null;
        startAt?: serializers.AzureLocalizedDateTime.Raw | null;
    }
}
