/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { SugerApi } from "@fern-api/suger";
import * as core from "../../../../core";

export const AzureProductVariantTrial: core.serialization.ObjectSchema<
    serializers.AzureProductVariantTrial.Raw,
    SugerApi.AzureProductVariantTrial
> = core.serialization.object({
    dateTimeRange: core.serialization
        .lazyObject(async () => (await import("../../..")).AzureLocalizedTimeRange)
        .optional(),
    duration: core.serialization.number().optional(),
    durationType: core.serialization.string().optional(),
    type: core.serialization.string().optional(),
});

export declare namespace AzureProductVariantTrial {
    interface Raw {
        dateTimeRange?: serializers.AzureLocalizedTimeRange.Raw | null;
        duration?: number | null;
        durationType?: string | null;
        type?: string | null;
    }
}
