/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { SugerApi } from "@fern-api/suger";
import * as core from "../../../../core";

export const AzureIntegration: core.serialization.ObjectSchema<
    serializers.AzureIntegration.Raw,
    SugerApi.AzureIntegration
> = core.serialization.object({
    cmaFullSyncDone: core.serialization.boolean().optional(),
    credential: core.serialization.lazyObject(async () => (await import("../../..")).AzureCredential).optional(),
});

export declare namespace AzureIntegration {
    interface Raw {
        cmaFullSyncDone?: boolean | null;
        credential?: serializers.AzureCredential.Raw | null;
    }
}
