/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { SugerApi } from "@fern-api/suger";
import * as core from "../../../../core";

export const AzureProductListingAsset: core.serialization.ObjectSchema<
    serializers.AzureProductListingAsset.Raw,
    SugerApi.AzureProductListingAsset
> = core.serialization.object({
    description: core.serialization.string().optional(),
    fileName: core.serialization.string().optional(),
    fileSasUri: core.serialization.string().optional(),
    friendlyName: core.serialization.string().optional(),
    id: core.serialization.string().optional(),
    order: core.serialization.number().optional(),
    publisherDefinedSasUri: core.serialization.string().optional(),
    resourceType: core.serialization.string().optional(),
    state: core.serialization.string().optional(),
    type: core.serialization.string().optional(),
});

export declare namespace AzureProductListingAsset {
    interface Raw {
        description?: string | null;
        fileName?: string | null;
        fileSasUri?: string | null;
        friendlyName?: string | null;
        id?: string | null;
        order?: number | null;
        publisherDefinedSasUri?: string | null;
        resourceType?: string | null;
        state?: string | null;
        type?: string | null;
    }
}
