/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { SugerApi } from "@fern-api/suger";
import * as core from "../../../../core";

export const AzureValidationResult: core.serialization.ObjectSchema<
    serializers.AzureValidationResult.Raw,
    SugerApi.AzureValidationResult
> = core.serialization.object({
    errorMessage: core.serialization.string().optional(),
    memberNames: core.serialization.list(core.serialization.string()).optional(),
});

export declare namespace AzureValidationResult {
    interface Raw {
        errorMessage?: string | null;
        memberNames?: string[] | null;
    }
}
