/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { SugerApi } from "@fern-api/suger";
import * as core from "../../../../core";

export const AzureMarket: core.serialization.ObjectSchema<serializers.AzureMarket.Raw, SugerApi.AzureMarket> =
    core.serialization.object({
        friendlyName: core.serialization.string().optional(),
        marketCode: core.serialization.string().optional(),
    });

export declare namespace AzureMarket {
    interface Raw {
        friendlyName?: string | null;
        marketCode?: string | null;
    }
}
