/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { SugerApi } from "@fern-api/suger";
import * as core from "../../../../core";

export const AzureProductListing: core.serialization.ObjectSchema<
    serializers.AzureProductListing.Raw,
    SugerApi.AzureProductListing
> = core.serialization.object({
    accessInformation: core.serialization.string().optional(),
    assets: core.serialization
        .list(core.serialization.lazyObject(async () => (await import("../../..")).AzureProductListingAsset))
        .optional(),
    compatibleProducts: core.serialization.list(core.serialization.string()).optional(),
    description: core.serialization.string().optional(),
    gettingStartedInstructions: core.serialization.string().optional(),
    id: core.serialization.string().optional(),
    keywords: core.serialization.list(core.serialization.string()).optional(),
    languageCode: core.serialization.string().optional(),
    listingContacts: core.serialization
        .list(core.serialization.lazyObject(async () => (await import("../../..")).AzureListingContact))
        .optional(),
    listingUris: core.serialization
        .list(core.serialization.lazyObject(async () => (await import("../../..")).AzureListingUri))
        .optional(),
    productDisplayName: core.serialization.string().optional(),
    publisherName: core.serialization.string().optional(),
    resourceType: core.serialization.string().optional(),
    shortDescription: core.serialization.string().optional(),
    summary: core.serialization.string().optional(),
    title: core.serialization.string().optional(),
});

export declare namespace AzureProductListing {
    interface Raw {
        accessInformation?: string | null;
        assets?: serializers.AzureProductListingAsset.Raw[] | null;
        compatibleProducts?: string[] | null;
        description?: string | null;
        gettingStartedInstructions?: string | null;
        id?: string | null;
        keywords?: string[] | null;
        languageCode?: string | null;
        listingContacts?: serializers.AzureListingContact.Raw[] | null;
        listingUris?: serializers.AzureListingUri.Raw[] | null;
        productDisplayName?: string | null;
        publisherName?: string | null;
        resourceType?: string | null;
        shortDescription?: string | null;
        summary?: string | null;
        title?: string | null;
    }
}
