/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { SugerApi } from "@fern-api/suger";
import * as core from "../../../../core";

export const AzureProductVariant: core.serialization.ObjectSchema<
    serializers.AzureProductVariant.Raw,
    SugerApi.AzureProductVariant
> = core.serialization.object({
    azureGovernmentCertifications: core.serialization
        .list(core.serialization.lazyObject(async () => (await import("../../..")).AzureGovernmentCertification))
        .optional(),
    cloudAvailabilities: core.serialization.list(core.serialization.string()).optional(),
    conversionPaths: core.serialization.string().optional(),
    extendedProperties: core.serialization
        .list(core.serialization.lazyObject(async () => (await import("../../..")).TypeValue))
        .optional(),
    externalId: core.serialization.property("externalID", core.serialization.string().optional()),
    featureAvailabilities: core.serialization
        .list(core.serialization.lazyObject(async () => (await import("../../..")).AzureProductFeatureAvailability))
        .optional(),
    friendlyName: core.serialization.string().optional(),
    id: core.serialization.string().optional(),
    leadGenId: core.serialization.property("leadGenID", core.serialization.string().optional()),
    referenceVariantId: core.serialization.property("referenceVariantID", core.serialization.string().optional()),
    resourceType: core.serialization.string().optional(),
    state: core.serialization.string().optional(),
});

export declare namespace AzureProductVariant {
    interface Raw {
        azureGovernmentCertifications?: serializers.AzureGovernmentCertification.Raw[] | null;
        cloudAvailabilities?: string[] | null;
        conversionPaths?: string | null;
        extendedProperties?: serializers.TypeValue.Raw[] | null;
        externalID?: string | null;
        featureAvailabilities?: serializers.AzureProductFeatureAvailability.Raw[] | null;
        friendlyName?: string | null;
        id?: string | null;
        leadGenID?: string | null;
        referenceVariantID?: string | null;
        resourceType?: string | null;
        state?: string | null;
    }
}
