/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { SugerApi } from "@fern-api/suger";
import * as core from "../../../../core";

export const AzureProductSubmission: core.serialization.ObjectSchema<
    serializers.AzureProductSubmission.Raw,
    SugerApi.AzureProductSubmission
> = core.serialization.object({
    areResourcesReady: core.serialization.boolean().optional(),
    friendlyName: core.serialization.string().optional(),
    id: core.serialization.string().optional(),
    pendingUpdateInfo: core.serialization
        .lazyObject(async () => (await import("../../..")).AzurePendingUpdateInfo)
        .optional(),
    publishedTimeInUtc: core.serialization.string().optional(),
    releaseNumber: core.serialization.number().optional(),
    resourceType: core.serialization.string().optional(),
    resources: core.serialization
        .list(core.serialization.lazyObject(async () => (await import("../../..")).TypeValue))
        .optional(),
    state: core.serialization.string().optional(),
    subState: core.serialization.string().optional(),
    targets: core.serialization
        .list(core.serialization.lazyObject(async () => (await import("../../..")).TypeValue))
        .optional(),
    variantResources: core.serialization
        .list(core.serialization.lazyObject(async () => (await import("../../..")).AzureVariantResource))
        .optional(),
});

export declare namespace AzureProductSubmission {
    interface Raw {
        areResourcesReady?: boolean | null;
        friendlyName?: string | null;
        id?: string | null;
        pendingUpdateInfo?: serializers.AzurePendingUpdateInfo.Raw | null;
        publishedTimeInUtc?: string | null;
        releaseNumber?: number | null;
        resourceType?: string | null;
        resources?: serializers.TypeValue.Raw[] | null;
        state?: string | null;
        subState?: string | null;
        targets?: serializers.TypeValue.Raw[] | null;
        variantResources?: serializers.AzureVariantResource.Raw[] | null;
    }
}
