/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { SugerApi } from "@fern-api/suger";
import * as core from "../../../../core";

export const AzureTerm: core.serialization.ObjectSchema<serializers.AzureTerm.Raw, SugerApi.AzureTerm> =
    core.serialization.object({
        chargeDuration: core.serialization.string().optional(),
        endDate: core.serialization.string().optional(),
        startDate: core.serialization.string().optional(),
        termUnit: core.serialization.string().optional(),
    });

export declare namespace AzureTerm {
    interface Raw {
        chargeDuration?: string | null;
        endDate?: string | null;
        startDate?: string | null;
        termUnit?: string | null;
    }
}
