/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { SugerApi } from "@fern-api/suger";
import * as core from "../../../../core";

export const AzureAudience: core.serialization.ObjectSchema<serializers.AzureAudience.Raw, SugerApi.AzureAudience> =
    core.serialization.object({
        description: core.serialization.string().optional(),
        id: core.serialization.string().optional(),
    });

export declare namespace AzureAudience {
    interface Raw {
        description?: string | null;
        id?: string | null;
    }
}
