/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { SugerApi } from "@fern-api/suger";
import * as core from "../../../../core";

export const AzurePrice: core.serialization.ObjectSchema<serializers.AzurePrice.Raw, SugerApi.AzurePrice> =
    core.serialization.object({
        currencyCode: core.serialization.string().optional(),
        openPrice: core.serialization.number().optional(),
        priceTierId: core.serialization.property("priceTierID", core.serialization.string().optional()),
    });

export declare namespace AzurePrice {
    interface Raw {
        currencyCode?: string | null;
        openPrice?: number | null;
        priceTierID?: string | null;
    }
}
