/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { SugerApi } from "@fern-api/suger";
import * as core from "../../../../core";

export const AzureProductProperty: core.serialization.ObjectSchema<
    serializers.AzureProductProperty.Raw,
    SugerApi.AzureProductProperty
> = core.serialization.object({
    additionalCategories: core.serialization.list(core.serialization.string()).optional(),
    appVersion: core.serialization.string().optional(),
    applicableProducts: core.serialization.list(core.serialization.string()).optional(),
    categories: core.serialization.list(core.serialization.string()).optional(),
    customAmendments: core.serialization.list(core.serialization.string()).optional(),
    extendedProperties: core.serialization.list(core.serialization.string()).optional(),
    globalAmendmentTerms: core.serialization.string().optional(),
    hideKeys: core.serialization.list(core.serialization.string()).optional(),
    id: core.serialization.string().optional(),
    industries: core.serialization.list(core.serialization.string()).optional(),
    marketingOnlyChange: core.serialization.boolean().optional(),
    productTags: core.serialization.list(core.serialization.string()).optional(),
    resourceType: core.serialization.string().optional(),
    submissionVersion: core.serialization.string().optional(),
    termsOfUse: core.serialization.string().optional(),
    useEnterpriseContract: core.serialization.boolean().optional(),
});

export declare namespace AzureProductProperty {
    interface Raw {
        additionalCategories?: string[] | null;
        appVersion?: string | null;
        applicableProducts?: string[] | null;
        categories?: string[] | null;
        customAmendments?: string[] | null;
        extendedProperties?: string[] | null;
        globalAmendmentTerms?: string | null;
        hideKeys?: string[] | null;
        id?: string | null;
        industries?: string[] | null;
        marketingOnlyChange?: boolean | null;
        productTags?: string[] | null;
        resourceType?: string | null;
        submissionVersion?: string | null;
        termsOfUse?: string | null;
        useEnterpriseContract?: boolean | null;
    }
}
