/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { SugerApi } from "@fern-api/suger";
import * as core from "../../../../core";

export const AzureMarketState: core.serialization.ObjectSchema<
    serializers.AzureMarketState.Raw,
    SugerApi.AzureMarketState
> = core.serialization.object({
    marketCode: core.serialization.string().optional(),
    state: core.serialization.string().optional(),
});

export declare namespace AzureMarketState {
    interface Raw {
        marketCode?: string | null;
        state?: string | null;
    }
}
