/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { SugerApi } from "@fern-api/suger";
import * as core from "../../../../core";

export const AzureCredential: core.serialization.ObjectSchema<
    serializers.AzureCredential.Raw,
    SugerApi.AzureCredential
> = core.serialization.object({
    clientId: core.serialization.property("clientID", core.serialization.string().optional()),
    clientSecret: core.serialization.string().optional(),
    clientSecretKey: core.serialization.string().optional(),
    resourceId: core.serialization.property("resourceID", core.serialization.string().optional()),
    tenantId: core.serialization.property("tenantID", core.serialization.string().optional()),
});

export declare namespace AzureCredential {
    interface Raw {
        clientID?: string | null;
        clientSecret?: string | null;
        clientSecretKey?: string | null;
        resourceID?: string | null;
        tenantID?: string | null;
    }
}
