/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { SugerApi } from "@fern-api/suger";
import * as core from "../../../../core";

export const AzureListingUri: core.serialization.ObjectSchema<
    serializers.AzureListingUri.Raw,
    SugerApi.AzureListingUri
> = core.serialization.object({
    displayText: core.serialization.string().optional(),
    subtype: core.serialization.string().optional(),
    type: core.serialization.string().optional(),
    uri: core.serialization.string().optional(),
});

export declare namespace AzureListingUri {
    interface Raw {
        displayText?: string | null;
        subtype?: string | null;
        type?: string | null;
        uri?: string | null;
    }
}
