/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { SugerApi } from "@fern-api/suger";
import * as core from "../../../../core";

export const AzureBuyerInfo: core.serialization.ObjectSchema<serializers.AzureBuyerInfo.Raw, SugerApi.AzureBuyerInfo> =
    core.serialization.object({
        billingAccountId: core.serialization.string().optional(),
        customerId: core.serialization.string().optional(),
        firstName: core.serialization.string().optional(),
        lastName: core.serialization.string().optional(),
    });

export declare namespace AzureBuyerInfo {
    interface Raw {
        billingAccountId?: string | null;
        customerId?: string | null;
        firstName?: string | null;
        lastName?: string | null;
    }
}
