/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { SugerApi } from "@fern-api/suger";
import * as core from "../../../../core";

export const AzureListingContact: core.serialization.ObjectSchema<
    serializers.AzureListingContact.Raw,
    SugerApi.AzureListingContact
> = core.serialization.object({
    email: core.serialization.string().optional(),
    name: core.serialization.string().optional(),
    phone: core.serialization.string().optional(),
    type: core.serialization.string().optional(),
    uri: core.serialization.string().optional(),
});

export declare namespace AzureListingContact {
    interface Raw {
        email?: string | null;
        name?: string | null;
        phone?: string | null;
        type?: string | null;
        uri?: string | null;
    }
}
