/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { SugerApi } from "@fern-api/suger";
import * as core from "../../../../core";

export const AzurePriceSchedule: core.serialization.ObjectSchema<
    serializers.AzurePriceSchedule.Raw,
    SugerApi.AzurePriceSchedule
> = core.serialization.object({
    priceCadence: core.serialization.lazyObject(async () => (await import("../../..")).AzurePriceCadence).optional(),
    pricingModel: core.serialization.string().optional(),
    pricingUnits: core.serialization
        .list(core.serialization.lazyObject(async () => (await import("../../..")).AzurePricingUnit))
        .optional(),
    retailPrice: core.serialization.lazyObject(async () => (await import("../../..")).AzurePrice).optional(),
});

export declare namespace AzurePriceSchedule {
    interface Raw {
        priceCadence?: serializers.AzurePriceCadence.Raw | null;
        pricingModel?: string | null;
        pricingUnits?: serializers.AzurePricingUnit.Raw[] | null;
        retailPrice?: serializers.AzurePrice.Raw | null;
    }
}
