/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { SugerApi } from "@fern-api/suger";
import * as core from "../../../../core";

export const AzurePendingUpdateInfo: core.serialization.ObjectSchema<
    serializers.AzurePendingUpdateInfo.Raw,
    SugerApi.AzurePendingUpdateInfo
> = core.serialization.object({
    status: core.serialization.string().optional(),
    updateType: core.serialization.string().optional(),
});

export declare namespace AzurePendingUpdateInfo {
    interface Raw {
        status?: string | null;
        updateType?: string | null;
    }
}
