/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { SugerApi } from "@fern-api/suger";
import * as core from "../../../../core";

export const AzureAdIdentifier: core.serialization.ObjectSchema<
    serializers.AzureAdIdentifier.Raw,
    SugerApi.AzureAdIdentifier
> = core.serialization.object({
    buyerInfo: core.serialization.lazyObject(async () => (await import("../../..")).AzureBuyerInfo).optional(),
    companyInfo: core.serialization.lazyObject(async () => (await import("../../..")).CompanyInfo).optional(),
    emailId: core.serialization.string().optional(),
    objectId: core.serialization.string().optional(),
    puid: core.serialization.string().optional(),
    tenantId: core.serialization.string().optional(),
});

export declare namespace AzureAdIdentifier {
    interface Raw {
        buyerInfo?: serializers.AzureBuyerInfo.Raw | null;
        companyInfo?: serializers.CompanyInfo.Raw | null;
        emailId?: string | null;
        objectId?: string | null;
        puid?: string | null;
        tenantId?: string | null;
    }
}
