/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { SugerApi } from "@fern-api/suger";
import * as core from "../../../../core";

export const AzureProductVariantPriceSchedule: core.serialization.ObjectSchema<
    serializers.AzureProductVariantPriceSchedule.Raw,
    SugerApi.AzureProductVariantPriceSchedule
> = core.serialization.object({
    dateTimeRange: core.serialization
        .lazyObject(async () => (await import("../../..")).AzureLocalizedTimeRange)
        .optional(),
    friendlyName: core.serialization.string().optional(),
    isBaseSchedule: core.serialization.boolean().optional(),
    marketCodes: core.serialization.list(core.serialization.string()).optional(),
    schedules: core.serialization
        .list(core.serialization.lazyObject(async () => (await import("../../..")).AzurePriceSchedule))
        .optional(),
});

export declare namespace AzureProductVariantPriceSchedule {
    interface Raw {
        dateTimeRange?: serializers.AzureLocalizedTimeRange.Raw | null;
        friendlyName?: string | null;
        isBaseSchedule?: boolean | null;
        marketCodes?: string[] | null;
        schedules?: serializers.AzurePriceSchedule.Raw[] | null;
    }
}
