/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { SugerApi } from "@fern-api/suger";
import * as core from "../../../../core";

export const BatchUsageEventOkResponse: core.serialization.ObjectSchema<
    serializers.BatchUsageEventOkResponse.Raw,
    SugerApi.BatchUsageEventOkResponse
> = core.serialization.object({
    count: core.serialization.number().optional(),
    result: core.serialization
        .list(core.serialization.lazyObject(async () => (await import("../../..")).UsageBatchEventOkMessage))
        .optional(),
});

export declare namespace BatchUsageEventOkResponse {
    interface Raw {
        count?: number | null;
        result?: serializers.UsageBatchEventOkMessage.Raw[] | null;
    }
}
