/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { SugerApi } from "@fern-api/suger";
import * as core from "../../../../core";

export const CompanyInfo: core.serialization.ObjectSchema<serializers.CompanyInfo.Raw, SugerApi.CompanyInfo> =
    core.serialization.object({
        addressLine1: core.serialization.string().optional(),
        addressLine2: core.serialization.string().optional(),
        city: core.serialization.string().optional(),
        country: core.serialization.string().optional(),
        emailDomain: core.serialization.string().optional(),
        name: core.serialization.string().optional(),
        postalCode: core.serialization.string().optional(),
        state: core.serialization.string().optional(),
    });

export declare namespace CompanyInfo {
    interface Raw {
        addressLine1?: string | null;
        addressLine2?: string | null;
        city?: string | null;
        country?: string | null;
        emailDomain?: string | null;
        name?: string | null;
        postalCode?: string | null;
        state?: string | null;
    }
}
