/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { SugerApi } from "@fern-api/suger";
import * as core from "../../../../core";

export const EntitlementTermInfo: core.serialization.ObjectSchema<
    serializers.EntitlementTermInfo.Raw,
    SugerApi.EntitlementTermInfo
> = core.serialization.object({
    type: core.serialization.string().optional(),
});

export declare namespace EntitlementTermInfo {
    interface Raw {
        type?: string | null;
    }
}
