/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { SugerApi } from "@fern-api/suger";
import * as core from "../../../../core";

export const Entitlement: core.serialization.ObjectSchema<serializers.Entitlement.Raw, SugerApi.Entitlement> =
    core.serialization.object({
        customerIdentifier: core.serialization.string().optional(),
        dimension: core.serialization.string().optional(),
        expirationDate: core.serialization.string().optional(),
        productCode: core.serialization.string().optional(),
    });

export declare namespace Entitlement {
    interface Raw {
        customerIdentifier?: string | null;
        dimension?: string | null;
        expirationDate?: string | null;
        productCode?: string | null;
    }
}
