/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { SugerApi } from "@fern-api/suger";
import * as core from "../../../../core";

export const GcpCommerceProducerServiceConfig: core.serialization.ObjectSchema<
    serializers.GcpCommerceProducerServiceConfig.Raw,
    SugerApi.GcpCommerceProducerServiceConfig
> = core.serialization.object({
    billing: core.serialization
        .lazyObject(async () => (await import("../../..")).GcpCommerceProducerServiceBilling)
        .optional(),
    metrics: core.serialization
        .list(core.serialization.lazyObject(async () => (await import("../../..")).GcpCommerceProducerPurchaseMetric))
        .optional(),
    name: core.serialization.string().optional(),
    producerProjectId: core.serialization.string().optional(),
    title: core.serialization.string().optional(),
});

export declare namespace GcpCommerceProducerServiceConfig {
    interface Raw {
        billing?: serializers.GcpCommerceProducerServiceBilling.Raw | null;
        metrics?: serializers.GcpCommerceProducerPurchaseMetric.Raw[] | null;
        name?: string | null;
        producerProjectId?: string | null;
        title?: string | null;
    }
}
