/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { SugerApi } from "@fern-api/suger";
import * as core from "../../../../core";

export const GcpCommerceProducerMarketingSpec: core.serialization.ObjectSchema<
    serializers.GcpCommerceProducerMarketingSpec.Raw,
    SugerApi.GcpCommerceProducerMarketingSpec
> = core.serialization.object({
    description: core.serialization.string().optional(),
    displayNames: core.serialization.list(core.serialization.string()).optional(),
    eulaUrl: core.serialization.string().optional(),
    externalMarketingUrl: core.serialization.string().optional(),
    icon: core.serialization.string().optional(),
    searchCategories: core.serialization.list(core.serialization.string()).optional(),
    searchDescription: core.serialization.string().optional(),
    searchKeywords: core.serialization.list(core.serialization.string()).optional(),
    shortTitle: core.serialization.string().optional(),
    supportSpec: core.serialization
        .lazyObject(async () => (await import("../../..")).GcpCommerceProducerSupportSpec)
        .optional(),
    title: core.serialization.string().optional(),
});

export declare namespace GcpCommerceProducerMarketingSpec {
    interface Raw {
        description?: string | null;
        displayNames?: string[] | null;
        eulaUrl?: string | null;
        externalMarketingUrl?: string | null;
        icon?: string | null;
        searchCategories?: string[] | null;
        searchDescription?: string | null;
        searchKeywords?: string[] | null;
        shortTitle?: string | null;
        supportSpec?: serializers.GcpCommerceProducerSupportSpec.Raw | null;
        title?: string | null;
    }
}
