/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { SugerApi } from "@fern-api/suger";
import * as core from "../../../../core";

export const GcpCommerceProducerPriceSubscription: core.serialization.ObjectSchema<
    serializers.GcpCommerceProducerPriceSubscription.Raw,
    SugerApi.GcpCommerceProducerPriceSubscription
> = core.serialization.object({
    period: core.serialization.string().optional(),
    price: core.serialization.lazyObject(async () => (await import("../../..")).GcpCommerceProducerPrice).optional(),
    taxCategoryOverride: core.serialization.string().optional(),
});

export declare namespace GcpCommerceProducerPriceSubscription {
    interface Raw {
        period?: string | null;
        price?: serializers.GcpCommerceProducerPrice.Raw | null;
        taxCategoryOverride?: string | null;
    }
}
