/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { SugerApi } from "@fern-api/suger";
import * as core from "../../../../core";

export const GcpCommerceProducerPriceTier: core.serialization.ObjectSchema<
    serializers.GcpCommerceProducerPriceTier.Raw,
    SugerApi.GcpCommerceProducerPriceTier
> = core.serialization.object({
    endUsageAmount: core.serialization.number().optional(),
    price: core.serialization.lazyObject(async () => (await import("../../..")).GcpCommerceProducerPrice).optional(),
    startUsageAmount: core.serialization.number().optional(),
});

export declare namespace GcpCommerceProducerPriceTier {
    interface Raw {
        endUsageAmount?: number | null;
        price?: serializers.GcpCommerceProducerPrice.Raw | null;
        startUsageAmount?: number | null;
    }
}
