/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { SugerApi } from "@fern-api/suger";
import * as core from "../../../../core";

export const GcpCommerceProducerPrice: core.serialization.ObjectSchema<
    serializers.GcpCommerceProducerPrice.Raw,
    SugerApi.GcpCommerceProducerPrice
> = core.serialization.object({
    currencyCode: core.serialization.string().optional(),
    nanos: core.serialization.number().optional(),
    units: core.serialization.number().optional(),
});

export declare namespace GcpCommerceProducerPrice {
    interface Raw {
        currencyCode?: string | null;
        nanos?: number | null;
        units?: number | null;
    }
}
