/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { SugerApi } from "@fern-api/suger";
import * as core from "../../../../core";

export const GcpCommerceProducerPriceInfo: core.serialization.ObjectSchema<
    serializers.GcpCommerceProducerPriceInfo.Raw,
    SugerApi.GcpCommerceProducerPriceInfo
> = core.serialization.object({
    description: core.serialization.string().optional(),
    priceModel: core.serialization.string().optional(),
    subscriptionPlans: core.serialization
        .list(
            core.serialization.lazyObject(async () => (await import("../../..")).GcpCommerceProducerPriceSubscription)
        )
        .optional(),
    usageFees: core.serialization
        .list(core.serialization.lazyObject(async () => (await import("../../..")).GcpCommerceProducerPriceUsage))
        .optional(),
});

export declare namespace GcpCommerceProducerPriceInfo {
    interface Raw {
        description?: string | null;
        priceModel?: string | null;
        subscriptionPlans?: serializers.GcpCommerceProducerPriceSubscription.Raw[] | null;
        usageFees?: serializers.GcpCommerceProducerPriceUsage.Raw[] | null;
    }
}
