/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { SugerApi } from "@fern-api/suger";
import * as core from "../../../../core";

export const GcpCommerceProducerServiceBilling: core.serialization.ObjectSchema<
    serializers.GcpCommerceProducerServiceBilling.Raw,
    SugerApi.GcpCommerceProducerServiceBilling
> = core.serialization.object({
    metrics: core.serialization.list(core.serialization.string()).optional(),
});

export declare namespace GcpCommerceProducerServiceBilling {
    interface Raw {
        metrics?: string[] | null;
    }
}
