/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { SugerApi } from "@fern-api/suger";
import * as core from "../../../../core";

export const GcpCommerceProducerSupportSpec: core.serialization.ObjectSchema<
    serializers.GcpCommerceProducerSupportSpec.Raw,
    SugerApi.GcpCommerceProducerSupportSpec
> = core.serialization.object({
    description: core.serialization.string().optional(),
    email: core.serialization.string().optional(),
    uri: core.serialization.string().optional(),
});

export declare namespace GcpCommerceProducerSupportSpec {
    interface Raw {
        description?: string | null;
        email?: string | null;
        uri?: string | null;
    }
}
