/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { SugerApi } from "@fern-api/suger";
import * as core from "../../../../core";

export const GcpCommerceProducerPurchaseSpec: core.serialization.ObjectSchema<
    serializers.GcpCommerceProducerPurchaseSpec.Raw,
    SugerApi.GcpCommerceProducerPurchaseSpec
> = core.serialization.object({
    metrics: core.serialization
        .list(core.serialization.lazyObject(async () => (await import("../../..")).GcpCommerceProducerPurchaseMetric))
        .optional(),
    purchaseOptionSpecs: core.serialization
        .list(core.serialization.lazyObject(async () => (await import("../../..")).GcpPurchasePlan))
        .optional(),
});

export declare namespace GcpCommerceProducerPurchaseSpec {
    interface Raw {
        metrics?: serializers.GcpCommerceProducerPurchaseMetric.Raw[] | null;
        purchaseOptionSpecs?: serializers.GcpPurchasePlan.Raw[] | null;
    }
}
