/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { SugerApi } from "@fern-api/suger";
import * as core from "../../../../core";

export const GcpCommerceProducerExternalAccountSpec: core.serialization.ObjectSchema<
    serializers.GcpCommerceProducerExternalAccountSpec.Raw,
    SugerApi.GcpCommerceProducerExternalAccountSpec
> = core.serialization.object({
    loginUri: core.serialization.string().optional(),
    signupUri: core.serialization.string().optional(),
    singleSignOnUri: core.serialization.string().optional(),
});

export declare namespace GcpCommerceProducerExternalAccountSpec {
    interface Raw {
        loginUri?: string | null;
        signupUri?: string | null;
        singleSignOnUri?: string | null;
    }
}
