/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { SugerApi } from "@fern-api/suger";
import * as core from "../../../../core";

export const GcpMarketplaceUserAccountApproval: core.serialization.ObjectSchema<
    serializers.GcpMarketplaceUserAccountApproval.Raw,
    SugerApi.GcpMarketplaceUserAccountApproval
> = core.serialization.object({
    name: core.serialization.string().optional(),
    reason: core.serialization.string().optional(),
    state: core.serialization.string().optional(),
    updateTime: core.serialization.string().optional(),
});

export declare namespace GcpMarketplaceUserAccountApproval {
    interface Raw {
        name?: string | null;
        reason?: string | null;
        state?: string | null;
        updateTime?: string | null;
    }
}
