/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { SugerApi } from "@fern-api/suger";
import * as core from "../../../../core";

export const GcpMarketplaceConsumer: core.serialization.ObjectSchema<
    serializers.GcpMarketplaceConsumer.Raw,
    SugerApi.GcpMarketplaceConsumer
> = core.serialization.object({
    project: core.serialization.string().optional(),
});

export declare namespace GcpMarketplaceConsumer {
    interface Raw {
        project?: string | null;
    }
}
