/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { SugerApi } from "@fern-api/suger";
import * as core from "../../../../core";

export const GcpMarketplaceEntitlement: core.serialization.ObjectSchema<
    serializers.GcpMarketplaceEntitlement.Raw,
    SugerApi.GcpMarketplaceEntitlement
> = core.serialization.object({
    account: core.serialization.string().optional(),
    consumers: core.serialization
        .list(core.serialization.lazyObject(async () => (await import("../../..")).GcpMarketplaceConsumer))
        .optional(),
    createTime: core.serialization.string().optional(),
    id: core.serialization.string().optional(),
    inputProperties: core.serialization.list(core.serialization.number()).optional(),
    messageToUser: core.serialization.string().optional(),
    name: core.serialization.string().optional(),
    newOfferDuration: core.serialization.string().optional(),
    newOfferEndTime: core.serialization.string().optional(),
    newPendingOffer: core.serialization.string().optional(),
    newPendingOfferDuration: core.serialization.string().optional(),
    newPendingPlan: core.serialization.string().optional(),
    newPlan: core.serialization.string().optional(),
    offer: core.serialization.string().optional(),
    offerDuration: core.serialization.string().optional(),
    offerEndTime: core.serialization.string().optional(),
    plan: core.serialization.string().optional(),
    product: core.serialization.string().optional(),
    productExternalName: core.serialization.string().optional(),
    provider: core.serialization.string().optional(),
    quoteExternalName: core.serialization.string().optional(),
    state: core.serialization.string().optional(),
    subscriptionEndTime: core.serialization.string().optional(),
    updateTime: core.serialization.string().optional(),
    usageReportingId: core.serialization.string().optional(),
});

export declare namespace GcpMarketplaceEntitlement {
    interface Raw {
        account?: string | null;
        consumers?: serializers.GcpMarketplaceConsumer.Raw[] | null;
        createTime?: string | null;
        id?: string | null;
        inputProperties?: number[] | null;
        messageToUser?: string | null;
        name?: string | null;
        newOfferDuration?: string | null;
        newOfferEndTime?: string | null;
        newPendingOffer?: string | null;
        newPendingOfferDuration?: string | null;
        newPendingPlan?: string | null;
        newPlan?: string | null;
        offer?: string | null;
        offerDuration?: string | null;
        offerEndTime?: string | null;
        plan?: string | null;
        product?: string | null;
        productExternalName?: string | null;
        provider?: string | null;
        quoteExternalName?: string | null;
        state?: string | null;
        subscriptionEndTime?: string | null;
        updateTime?: string | null;
        usageReportingId?: string | null;
    }
}
