/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { SugerApi } from "@fern-api/suger";
import * as core from "../../../../core";

export const GcpUserInfo: core.serialization.ObjectSchema<serializers.GcpUserInfo.Raw, SugerApi.GcpUserInfo> =
    core.serialization.object({
        roles: core.serialization.list(core.serialization.string()).optional(),
        userIdentity: core.serialization.property("user_identity", core.serialization.string().optional()),
    });

export declare namespace GcpUserInfo {
    interface Raw {
        roles?: string[] | null;
        user_identity?: string | null;
    }
}
