/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { SugerApi } from "@fern-api/suger";
import * as core from "../../../../core";

export const Header: core.serialization.Schema<serializers.Header.Raw, SugerApi.Header> = core.serialization.record(
    core.serialization.string(),
    core.serialization.list(core.serialization.string())
);

export declare namespace Header {
    type Raw = Record<string, string[]>;
}
