/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { SugerApi } from "@fern-api/suger";
import * as core from "../../../../core";

export const IdentityIntegration: core.serialization.ObjectSchema<
    serializers.IdentityIntegration.Raw,
    SugerApi.IdentityIntegration
> = core.serialization.object({
    createdBy: core.serialization.string().optional(),
    creationTime: core.serialization.string().optional(),
    info: core.serialization.lazyObject(async () => (await import("../../..")).IntegrationInfo).optional(),
    lastUpdateTime: core.serialization.string().optional(),
    lastUpdatedBy: core.serialization.string().optional(),
    organizationId: core.serialization.property("organizationID", core.serialization.string().optional()),
    partner: core.serialization.string().optional(),
    service: core.serialization.string().optional(),
    status: core.serialization.string().optional(),
});

export declare namespace IdentityIntegration {
    interface Raw {
        createdBy?: string | null;
        creationTime?: string | null;
        info?: serializers.IntegrationInfo.Raw | null;
        lastUpdateTime?: string | null;
        lastUpdatedBy?: string | null;
        organizationID?: string | null;
        partner?: string | null;
        service?: string | null;
        status?: string | null;
    }
}
