/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { SugerApi } from "@fern-api/suger";
import * as core from "../../../../core";

export const IncludedBaseQuantity: core.serialization.ObjectSchema<
    serializers.IncludedBaseQuantity.Raw,
    SugerApi.IncludedBaseQuantity
> = core.serialization.object({
    isInfinite: core.serialization.boolean().optional(),
    quantity: core.serialization.number().optional(),
    recurringUnit: core.serialization.string().optional(),
});

export declare namespace IncludedBaseQuantity {
    interface Raw {
        isInfinite?: boolean | null;
        quantity?: number | null;
        recurringUnit?: string | null;
    }
}
