/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { SugerApi } from "@fern-api/suger";
import * as core from "../../../../core";

export const Metadata: core.serialization.Schema<serializers.Metadata.Raw, SugerApi.Metadata> =
    core.serialization.unknown();

export declare namespace Metadata {
    type Raw = unknown;
}
