/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { SugerApi } from "@fern-api/suger";
import * as core from "../../../../core";

export const MeteringUsageRecordReport: core.serialization.ObjectSchema<
    serializers.MeteringUsageRecordReport.Raw,
    SugerApi.MeteringUsageRecordReport
> = core.serialization.object({
    creationTime: core.serialization.string().optional(),
    entitlementId: core.serialization.property("entitlementID", core.serialization.string().optional()),
    entitlementTermId: core.serialization.property("entitlementTermID", core.serialization.string().optional()),
    id: core.serialization.string().optional(),
    info: core.serialization
        .lazyObject(async () => (await import("../../..")).MeteringUsageRecordReportInfo)
        .optional(),
    organizationId: core.serialization.property("organizationID", core.serialization.string().optional()),
    productId: core.serialization.property("productID", core.serialization.string().optional()),
});

export declare namespace MeteringUsageRecordReport {
    interface Raw {
        creationTime?: string | null;
        entitlementID?: string | null;
        entitlementTermID?: string | null;
        id?: string | null;
        info?: serializers.MeteringUsageRecordReportInfo.Raw | null;
        organizationID?: string | null;
        productID?: string | null;
    }
}
