/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { SugerApi } from "@fern-api/suger";
import * as core from "../../../../core";

export const MeteringUsageRecordGroup: core.serialization.ObjectSchema<
    serializers.MeteringUsageRecordGroup.Raw,
    SugerApi.MeteringUsageRecordGroup
> = core.serialization.object({
    creationTime: core.serialization.string().optional(),
    entitlementId: core.serialization.property("entitlementID", core.serialization.string().optional()),
    id: core.serialization.string().optional(),
    lastUpdateTime: core.serialization.string().optional(),
    organizationId: core.serialization.property("organizationID", core.serialization.string().optional()),
    serialId: core.serialization.property("serialID", core.serialization.number().optional()),
    status: core.serialization.string().optional(),
    usageRecordReportId: core.serialization.property("usageRecordReportID", core.serialization.string().optional()),
});

export declare namespace MeteringUsageRecordGroup {
    interface Raw {
        creationTime?: string | null;
        entitlementID?: string | null;
        id?: string | null;
        lastUpdateTime?: string | null;
        organizationID?: string | null;
        serialID?: number | null;
        status?: string | null;
        usageRecordReportID?: string | null;
    }
}
