/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { SugerApi } from "@fern-api/suger";
import * as core from "../../../../core";

export const MeteringUsageRecordReportInfo: core.serialization.ObjectSchema<
    serializers.MeteringUsageRecordReportInfo.Raw,
    SugerApi.MeteringUsageRecordReportInfo
> = core.serialization.object({
    awsMeteringResponse: core.serialization
        .lazyObject(async () => (await import("../../..")).BatchMeterUsageOutput)
        .optional(),
    azureMeteringResponse: core.serialization
        .lazyObject(async () => (await import("../../..")).BatchUsageEventOkResponse)
        .optional(),
    commitAmount: core.serialization.number().optional(),
    creditAmount: core.serialization.number().optional(),
    endTime: core.serialization.string().optional(),
    gcpMeteringResponse: core.serialization
        .lazyObject(async () => (await import("../../..")).ReportResponse)
        .optional(),
    startTime: core.serialization.string().optional(),
    usageRecordGroupIds: core.serialization.list(core.serialization.string()).optional(),
    usedCommitAmount: core.serialization.number().optional(),
    usedCommitAmountIncrement: core.serialization.number().optional(),
    usedCreditAmount: core.serialization.number().optional(),
    usedCreditAmountIncrement: core.serialization.number().optional(),
});

export declare namespace MeteringUsageRecordReportInfo {
    interface Raw {
        awsMeteringResponse?: serializers.BatchMeterUsageOutput.Raw | null;
        azureMeteringResponse?: serializers.BatchUsageEventOkResponse.Raw | null;
        commitAmount?: number | null;
        creditAmount?: number | null;
        endTime?: string | null;
        gcpMeteringResponse?: serializers.ReportResponse.Raw | null;
        startTime?: string | null;
        usageRecordGroupIds?: string[] | null;
        usedCommitAmount?: number | null;
        usedCommitAmountIncrement?: number | null;
        usedCreditAmount?: number | null;
        usedCreditAmountIncrement?: number | null;
    }
}
