/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { SugerApi } from "@fern-api/suger";
import * as core from "../../../../core";

export const PaymentInstallment: core.serialization.ObjectSchema<
    serializers.PaymentInstallment.Raw,
    SugerApi.PaymentInstallment
> = core.serialization.object({
    amount: core.serialization.number().optional(),
    chargeOn: core.serialization.string().optional(),
});

export declare namespace PaymentInstallment {
    interface Raw {
        amount?: number | null;
        chargeOn?: string | null;
    }
}
