/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { SugerApi } from "@fern-api/suger";
import * as core from "../../../../core";

export const ReportError: core.serialization.ObjectSchema<serializers.ReportError.Raw, SugerApi.ReportError> =
    core.serialization.object({
        operationId: core.serialization.string().optional(),
        status: core.serialization.lazyObject(async () => (await import("../../..")).Status).optional(),
    });

export declare namespace ReportError {
    interface Raw {
        operationId?: string | null;
        status?: serializers.Status.Raw | null;
    }
}
