/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { SugerApi } from "@fern-api/suger";
import * as core from "../../../../core";

export const RevenueRecord: core.serialization.ObjectSchema<serializers.RevenueRecord.Raw, SugerApi.RevenueRecord> =
    core.serialization.object({
        amount: core.serialization.number().optional(),
        date: core.serialization.string().optional(),
    });

export declare namespace RevenueRecord {
    interface Raw {
        amount?: number | null;
        date?: string | null;
    }
}
