/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { SugerApi } from "@fern-api/suger";
import * as core from "../../../../core";

export const Tag: core.serialization.ObjectSchema<serializers.Tag.Raw, SugerApi.Tag> = core.serialization.object({
    key: core.serialization.string().optional(),
    value: core.serialization.string().optional(),
});

export declare namespace Tag {
    interface Raw {
        key?: string | null;
        value?: string | null;
    }
}
