/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { SugerApi } from "@fern-api/suger";
import * as core from "../../../../core";

export const TypeValue: core.serialization.ObjectSchema<serializers.TypeValue.Raw, SugerApi.TypeValue> =
    core.serialization.object({
        type: core.serialization.string().optional(),
        value: core.serialization.string().optional(),
    });

export declare namespace TypeValue {
    interface Raw {
        type?: string | null;
        value?: string | null;
    }
}
