/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { SugerApi } from "@fern-api/suger";
import * as core from "../../../../core";

export const UsageCount: core.serialization.ObjectSchema<serializers.UsageCount.Raw, SugerApi.UsageCount> =
    core.serialization.object({
        creditCount: core.serialization.number().optional(),
        includedCount: core.serialization.number().optional(),
        reportedCount: core.serialization.number().optional(),
    });

export declare namespace UsageCount {
    interface Raw {
        creditCount?: number | null;
        includedCount?: number | null;
        reportedCount?: number | null;
    }
}
