/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { SugerApi } from "@fern-api/suger";
import * as core from "../../../../core";

export const UsageEventConflictResponseAdditionalInfo: core.serialization.ObjectSchema<
    serializers.UsageEventConflictResponseAdditionalInfo.Raw,
    SugerApi.UsageEventConflictResponseAdditionalInfo
> = core.serialization.object({
    acceptedMessage: core.serialization
        .lazyObject(async () => (await import("../../..")).UsageEventOkResponse)
        .optional(),
});

export declare namespace UsageEventConflictResponseAdditionalInfo {
    interface Raw {
        acceptedMessage?: serializers.UsageEventOkResponse.Raw | null;
    }
}
