/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { SugerApi } from "@fern-api/suger";
import * as core from "../../../../core";

export const UsageRecord: core.serialization.ObjectSchema<serializers.UsageRecord.Raw, SugerApi.UsageRecord> =
    core.serialization.object({
        customerIdentifier: core.serialization.string().optional(),
        dimension: core.serialization.string().optional(),
        quantity: core.serialization.number().optional(),
        timestamp: core.serialization.string().optional(),
        usageAllocations: core.serialization
            .list(core.serialization.lazyObject(async () => (await import("../../..")).UsageAllocation))
            .optional(),
    });

export declare namespace UsageRecord {
    interface Raw {
        customerIdentifier?: string | null;
        dimension?: string | null;
        quantity?: number | null;
        timestamp?: string | null;
        usageAllocations?: serializers.UsageAllocation.Raw[] | null;
    }
}
