/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { SugerApi } from "@fern-api/suger";
import * as core from "../../../../core";

export const UsageAllocation: core.serialization.ObjectSchema<
    serializers.UsageAllocation.Raw,
    SugerApi.UsageAllocation
> = core.serialization.object({
    allocatedUsageQuantity: core.serialization.number().optional(),
    tags: core.serialization.list(core.serialization.lazyObject(async () => (await import("../../..")).Tag)).optional(),
});

export declare namespace UsageAllocation {
    interface Raw {
        allocatedUsageQuantity?: number | null;
        tags?: serializers.Tag.Raw[] | null;
    }
}
