/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { SugerApi } from "@fern-api/suger";
import * as core from "../../../../core";

export const UsageRecordResult: core.serialization.ObjectSchema<
    serializers.UsageRecordResult.Raw,
    SugerApi.UsageRecordResult
> = core.serialization.object({
    meteringRecordId: core.serialization.string().optional(),
    status: core.serialization.string().optional(),
    usageRecord: core.serialization.lazyObject(async () => (await import("../../..")).UsageRecord).optional(),
});

export declare namespace UsageRecordResult {
    interface Raw {
        meteringRecordId?: string | null;
        status?: string | null;
        usageRecord?: serializers.UsageRecord.Raw | null;
    }
}
