/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { SugerApi } from "@fern-api/suger";
import * as core from "../../../../core";

export const WorkloadEntitlementTerm: core.serialization.ObjectSchema<
    serializers.WorkloadEntitlementTerm.Raw,
    SugerApi.WorkloadEntitlementTerm
> = core.serialization.object({
    buyerId: core.serialization.property("buyerID", core.serialization.string().optional()),
    commitAmount: core.serialization.number().optional(),
    creditAmount: core.serialization.number().optional(),
    endTime: core.serialization.string().optional(),
    entitlementId: core.serialization.property("entitlementID", core.serialization.string().optional()),
    entitlementInfo: core.serialization.lazyObject(async () => (await import("../../..")).EntitlementInfo).optional(),
    externalEntitlementId: core.serialization.property("externalEntitlementID", core.serialization.string().optional()),
    id: core.serialization.string().optional(),
    info: core.serialization.lazyObject(async () => (await import("../../..")).EntitlementTermInfo).optional(),
    offerId: core.serialization.property("offerID", core.serialization.string().optional()),
    organizationId: core.serialization.property("organizationID", core.serialization.string().optional()),
    partner: core.serialization.string().optional(),
    productId: core.serialization.property("productID", core.serialization.string().optional()),
    service: core.serialization.string().optional(),
    startTime: core.serialization.string().optional(),
    usedCommitAmount: core.serialization.number().optional(),
    usedCreditAmount: core.serialization.number().optional(),
});

export declare namespace WorkloadEntitlementTerm {
    interface Raw {
        buyerID?: string | null;
        commitAmount?: number | null;
        creditAmount?: number | null;
        endTime?: string | null;
        entitlementID?: string | null;
        entitlementInfo?: serializers.EntitlementInfo.Raw | null;
        externalEntitlementID?: string | null;
        id?: string | null;
        info?: serializers.EntitlementTermInfo.Raw | null;
        offerID?: string | null;
        organizationID?: string | null;
        partner?: string | null;
        productID?: string | null;
        service?: string | null;
        startTime?: string | null;
        usedCommitAmount?: number | null;
        usedCreditAmount?: number | null;
    }
}
