/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { SugerApi } from "@fern-api/suger";
import * as core from "../../../../core";

export const WorkloadOffer: core.serialization.ObjectSchema<serializers.WorkloadOffer.Raw, SugerApi.WorkloadOffer> =
    core.serialization.object({
        createdBy: core.serialization.string().optional(),
        creationTime: core.serialization.string().optional(),
        endTime: core.serialization.string().optional(),
        expireTime: core.serialization.string().optional(),
        externalId: core.serialization.property("externalID", core.serialization.string().optional()),
        id: core.serialization.string().optional(),
        info: core.serialization.lazyObject(async () => (await import("../../..")).OfferInfo).optional(),
        lastUpdateTime: core.serialization.string().optional(),
        lastUpdatedBy: core.serialization.string().optional(),
        name: core.serialization.string().optional(),
        offerType: core.serialization.string().optional(),
        organizationId: core.serialization.property("organizationID", core.serialization.string().optional()),
        partner: core.serialization.string().optional(),
        productId: core.serialization.property("productID", core.serialization.string().optional()),
        service: core.serialization.string().optional(),
        status: core.serialization.string().optional(),
    });

export declare namespace WorkloadOffer {
    interface Raw {
        createdBy?: string | null;
        creationTime?: string | null;
        endTime?: string | null;
        expireTime?: string | null;
        externalID?: string | null;
        id?: string | null;
        info?: serializers.OfferInfo.Raw | null;
        lastUpdateTime?: string | null;
        lastUpdatedBy?: string | null;
        name?: string | null;
        offerType?: string | null;
        organizationID?: string | null;
        partner?: string | null;
        productID?: string | null;
        service?: string | null;
        status?: string | null;
    }
}
