/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { SugerApi } from "@fern-api/suger";
import * as core from "../../../../core";

export const WorkloadProduct: core.serialization.ObjectSchema<
    serializers.WorkloadProduct.Raw,
    SugerApi.WorkloadProduct
> = core.serialization.object({
    createdBy: core.serialization.string().optional(),
    creationTime: core.serialization.string().optional(),
    externalId: core.serialization.property("externalID", core.serialization.string().optional()),
    fulfillmentUrl: core.serialization.string().optional(),
    id: core.serialization.string().optional(),
    info: core.serialization.lazyObject(async () => (await import("../../..")).ProductInfo).optional(),
    lastUpdateTime: core.serialization.string().optional(),
    lastUpdatedBy: core.serialization.string().optional(),
    name: core.serialization.string().optional(),
    organizationId: core.serialization.property("organizationID", core.serialization.string().optional()),
    partner: core.serialization.string().optional(),
    productType: core.serialization.string().optional(),
    service: core.serialization.string().optional(),
    status: core.serialization.string().optional(),
});

export declare namespace WorkloadProduct {
    interface Raw {
        createdBy?: string | null;
        creationTime?: string | null;
        externalID?: string | null;
        fulfillmentUrl?: string | null;
        id?: string | null;
        info?: serializers.ProductInfo.Raw | null;
        lastUpdateTime?: string | null;
        lastUpdatedBy?: string | null;
        name?: string | null;
        organizationID?: string | null;
        partner?: string | null;
        productType?: string | null;
        service?: string | null;
        status?: string | null;
    }
}
