/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { SugerApi } from "@fern-api/suger";
import * as core from "../../../../core";

export const WorkloadEntitlement: core.serialization.ObjectSchema<
    serializers.WorkloadEntitlement.Raw,
    SugerApi.WorkloadEntitlement
> = core.serialization.object({
    buyerId: core.serialization.property("buyerID", core.serialization.string().optional()),
    creationTime: core.serialization.string().optional(),
    endTime: core.serialization.string().optional(),
    entitlementTermId: core.serialization.property("entitlementTermID", core.serialization.string().optional()),
    externalBuyerId: core.serialization.property("externalBuyerID", core.serialization.string().optional()),
    externalId: core.serialization.property("externalID", core.serialization.string().optional()),
    externalProductId: core.serialization.property("externalProductID", core.serialization.string().optional()),
    id: core.serialization.string().optional(),
    info: core.serialization.lazyObject(async () => (await import("../../..")).EntitlementInfo).optional(),
    lastUpdateTime: core.serialization.string().optional(),
    name: core.serialization.string().optional(),
    offerId: core.serialization.property("offerID", core.serialization.string().optional()),
    organizationId: core.serialization.property("organizationID", core.serialization.string().optional()),
    partner: core.serialization.string().optional(),
    productId: core.serialization.property("productID", core.serialization.string().optional()),
    service: core.serialization.string().optional(),
    startTime: core.serialization.string().optional(),
    status: core.serialization.string().optional(),
    type: core.serialization.string().optional(),
});

export declare namespace WorkloadEntitlement {
    interface Raw {
        buyerID?: string | null;
        creationTime?: string | null;
        endTime?: string | null;
        entitlementTermID?: string | null;
        externalBuyerID?: string | null;
        externalID?: string | null;
        externalProductID?: string | null;
        id?: string | null;
        info?: serializers.EntitlementInfo.Raw | null;
        lastUpdateTime?: string | null;
        name?: string | null;
        offerID?: string | null;
        organizationID?: string | null;
        partner?: string | null;
        productID?: string | null;
        service?: string | null;
        startTime?: string | null;
        status?: string | null;
        type?: string | null;
    }
}
